// RCX RTK Datalogger — wiring knowledge graph logical physics model

CREATE (esp32:Device {id: 'esp32', name: 'ESP32-S3-LCD-1.47B', type: 'MCU board', manufacturer: 'Waveshare', input_power: '5V via onboard USB-C connector', logic_level: '3.3V', physical_position_status: 'partial: external-header side and order are captured; millimeter pin coordinates are not yet captured', notes: 'ESP32-S3 board with onboard LCD, SD card, IMU, USB-C power/data, and left and right external GPIO headers.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'primary', diagram_group: 'controller', diagram_order: 10})
CREATE (lg290p:Device {id: 'lg290p', name: 'LG290P RTK GNSS module', type: 'GNSS receiver', voltage_in: '3.3V', logic_level: '3.3V', physical_position_status: 'connector ownership is captured; pin order and millimeter coordinates are not yet captured', notes: 'GNSS module 3.3V and GND leads are doubled into the VCC and GND positions of the SN65 4-pin plug, which is fed from the ESP32 3-pin power plug. UART connector is physically on the GPS module; the harness plugs into it with a JST SH cable plug.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'primary', diagram_group: 'gnss', diagram_order: 30})
CREATE (sn65:Device {id: 'sn65', name: 'SN65HVD230 CAN transceiver module', type: 'CAN transceiver breakout', voltage_in: '3.3V', logic_level: '3.3V', can_physical_layer: 'ISO 11898-2 high-speed CAN', physical_position_status: 'dimensioned from user-supplied STEP/STL', coordinate_frame: 'sn65_component_side_xz_v1', cad_source_step: 'CAN Transiver SN65HVD230.step', cad_source_stl: 'CAN Transiver SN65HVD230.stl', assembly_size_x_mm: 32.4903, assembly_size_y_mm: 10.2756, assembly_height_mm: 13.7764, notes: '3.3V CAN transceiver used as receive interface for vehicle CAN. TXD is wired but firmware may operate in listen-only mode.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'primary', diagram_group: 'can', diagram_order: 40})
CREATE (fan:Device {id: 'fan', name: '5V cooling fan', type: 'two-wire DC brushless fan', voltage_in: '5V', leads: 2, lead_termination: 'flying leads, no connector at the fan', control: 'none; runs whenever the board 5V rail is live', notes: 'Powered from the USB VBUS rail: +5V lead in the 5V position and ground doubled into the GND position of the ESP32 3-pin power plug.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'primary', diagram_group: 'thermal', diagram_order: 25})
CREATE (esp32_usb_c:Connector {id: 'esp32_usb_c', name: 'ESP32 onboard USB-C connector', device: 'esp32', type: 'USB-C receptacle', role: '5V power input and native USB data (USB Serial/JTAG) for firmware upload and serial monitor', physical_location: 'top edge of ESP32 board', board_side: 'top', notes: 'External 5V USB-C power is applied here. D+ and D- run on-board to ESP32-S3 GPIO20 and GPIO19 (native USB, no USB-UART bridge); the Arduino IDE uploads and monitors through this port.', data_interface: 'native USB Serial/JTAG', data_pins: 'GPIO19 USB_D-, GPIO20 USB_D+', physical_model: 'Connector is physically mounted on and logically owned by the ESP32-S3 board.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', interface_exposure: 'external', external_interface: true, interface_type: 'power_usb', cover_label: 'USB-C / 5V INPUT', cover_order: 10, diagram_level: 'primary', diagram_group: 'external_interface', diagram_order: 15})
CREATE (lg290p_uart_connector:Connector {id: 'lg290p_uart_connector', name: 'LG290P onboard UART connector', type: 'JST SH 1.0 mm 4-pin header', series: 'JST SH', positions: 4, nominal_pitch_mm: 1.0, user_gender: 'male header', identification: 'inferred from the Waveshare LG290P GNSS RTK Module documentation (UART on an SH1.0 4-pin connector); confirm against the board in hand', device: 'lg290p', pins: '3.3V, GND, TX, RX', notes: 'This connector is physically on the GPS module, not a separate inline harness connector.', physical_model: 'Connector is physically mounted on and logically owned by the LG290P module.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'detail'})
CREATE (sn65_logic_power_connector:Connector {id: 'sn65_logic_power_connector', name: 'SN65HVD230 4-pin logic/power header', type: '1x4 male pin header', user_gender: 'male header', device: 'sn65', positions: 4, nominal_pitch_mm: 2.54, measured_pitch_mm: 2.52, pins_component_side_top_to_bottom: ['VCC', 'GND', 'RXD', 'TXD'], physical_edge: 'logic-header end', contact_direction: '-X in sn65_component_side_xz_v1', notes: 'Carries 3.3V, ground, TWAI RXD, and TWAI TXD between the ESP32 header and the CAN transceiver module.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'detail'})
CREATE (can_logic_power_plug:Connector {id: 'can_logic_power_plug', name: 'SN65 4-pin logic/power plug', type: '4-position housing', user_gender: 'female housing', positions: 4, nominal_pitch_mm: 2.54, pins_top_to_bottom: ['VCC', 'GND', 'RXD', 'TXD'], notes: 'Plugs onto the SN65 1x4 logic/power header. The VCC and GND positions each hold two wires: the LG290P lead and the lead to the ESP32 3-pin power plug, which splices GPS power onto the CAN module supply.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'primary', diagram_group: 'can', diagram_order: 38})
CREATE (esp32_power_plug:Connector {id: 'esp32_power_plug', name: 'ESP32 3-pin power plug', type: '3-position housing', user_gender: 'female housing', positions: 3, nominal_pitch_mm: 2.54, notes: 'Plugs onto ESP32 left-header positions 1 to 3 (5V, GND, 3V3(OUT)) and carries all three power leads to the board. The GND position holds two wires: the ground lead from the SN65 4-pin plug and the fan ground.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'primary', diagram_group: 'power', diagram_order: 12})
CREATE (sn65_can_screw_terminal:Connector {id: 'sn65_can_screw_terminal', name: 'SN65HVD230 CAN screw terminal', type: '2-position PCB screw terminal', device: 'sn65', positions: 2, preferred_connection: false, position_1_signal: 'CANL', position_2_signal: 'CANH', component_side_order: 'CANL upper, CANH lower', measured_center_spacing_mm: 4.7390, notes: 'CANH and CANL screw terminals are electrically parallel with the nearby plated pads. Not used: the CAN pigtail plugs onto header pins fitted in the parallel pads.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'detail'})
CREATE (sn65_can_parallel_pads:Connector {id: 'sn65_can_parallel_pads', name: 'SN65HVD230 parallel CAN header', type: '1x2 male pin header in the parallel CAN pads', device: 'sn65', positions: 2, nominal_pitch_mm: 2.54, user_gender: 'male header', preferred_connection: true, position_1_signal: 'CANL', position_2_signal: 'CANH', component_side_order: 'CANL upper, CANH lower', measured_center_spacing_mm: 2.52, notes: 'Male header pins in the plated pads that are electrically parallel with the CAN screw terminals. The transceiver CAN pigtail plugs on here for every vehicle.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'detail'})
CREATE (can_pigtail_socket:Connector {id: 'can_pigtail_socket', name: 'CAN pigtail Dupont female housing', type: '2-position Dupont housing', series: 'Dupont', positions: 2, nominal_pitch_mm: 2.54, user_gender: 'female housing', mounting: 'on the transceiver CAN pigtail', pin_1_signal: 'CANL', pin_2_signal: 'CANH', housing_status: 'assumed one 2-position housing; not recorded', notes: 'Plugs onto the male header pins in the SN65 parallel CAN pads. Pin 1 is CANL; pin 2 is CANH.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', interface_exposure: 'external', external_interface: true, interface_type: 'vehicle_can', cover_label: 'VEHICLE CAN', cover_order: 30, diagram_level: 'primary', diagram_group: 'can', diagram_order: 41})
CREATE (can_pigtail_plug:Connector {id: 'can_pigtail_plug', name: 'CAN pigtail Dupont male plug', type: '2-position Dupont male housing', series: 'Dupont', positions: 2, nominal_pitch_mm: 2.54, user_gender: 'male plug', mounting: 'on the transceiver CAN pigtail', pin_1_signal: 'CANL', pin_2_signal: 'CANH', housing_status: 'assumed one 2-position housing; not recorded', notes: 'Male Dupont pins at the free end of the pigtail. The vehicle lead in use plugs on here; with no vehicle attached it is left free.', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'external_harness', diagram_order: 55})
CREATE (positap_lead_socket:Connector {id: 'positap_lead_socket', variants: ['var_718_drive', 'var_718_chassis', 'var_987_2_drive'], name: 'PosiTap lead Dupont female housing', type: '2-position Dupont housing', series: 'Dupont', positions: 2, nominal_pitch_mm: 2.54, user_gender: 'female housing', mounting: 'on the removable PosiTap lead', location: 'removable harness', pin_1_signal: 'CANL', pin_2_signal: 'CANH', housing_status: 'assumed one 2-position housing; not recorded', notes: 'Takes the male Dupont pins of the transceiver CAN pigtail. Pin 1 is CANL; pin 2 is CANH.', enclosure_scope: 'external', external_removable: true, diagram_level: 'primary', diagram_group: 'external_harness', diagram_order: 60})
CREATE (sn65_frame:CoordinateFrame {id: 'sn65_component_side_xz_v1', device: 'sn65', name: 'SN65 component-side board coordinate frame', units: 'mm', source: 'user-supplied STEP/STL', drawing_plane: 'STL X-Z projection', origin: 'STL minimum X and minimum Z', x_axis: 'logic header toward screw terminal', y_axis: 'lower CANH side toward upper CANL side; equals STL +Z', height_axis: 'STL +Y away from PCB base', position_accuracy_mm: 0.05})
CREATE (positap_can_h:Connector {id: 'positap_can_h', variants: ['var_718_drive', 'var_718_chassis', 'var_987_2_drive'], name: 'PosiTap CAN-H', type: 'direct tap connector', role: 'tap onto vehicle CAN-H', signal: 'CAN-H', polarity: '+', tap_lead_color: 'white', mapping_scope: 'Vehicle-specific bus and wire color are defined on TAPS_VEHICLE_CAN relationships.', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'vehicle_tap', diagram_order: 70})
CREATE (positap_can_l:Connector {id: 'positap_can_l', variants: ['var_718_drive', 'var_718_chassis', 'var_987_2_drive'], name: 'PosiTap CAN-L', type: 'direct tap connector', role: 'tap onto vehicle CAN-L', signal: 'CAN-L', polarity: '-', tap_lead_color: 'green', mapping_scope: 'Vehicle-specific bus and wire color are defined on TAPS_VEHICLE_CAN relationships.', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'vehicle_tap', diagram_order: 71})


CREATE (esp32_header_left:Connector {id: 'esp32_header_left', name: 'ESP32 left pin header', device: 'esp32', type: '1x9 male pin header', user_gender: 'male header', positions: 9, nominal_pitch_mm: 2.54, board_side: 'left', position_order: 'header_order 1 at the top', notes: 'Left external GPIO header of the ESP32-S3-LCD-1.47B.'})
CREATE (esp32_header_right:Connector {id: 'esp32_header_right', name: 'ESP32 right pin header', device: 'esp32', type: '1x9 male pin header', user_gender: 'male header', positions: 9, nominal_pitch_mm: 2.54, board_side: 'right', position_order: 'header_order 1 at the top', notes: 'Right external GPIO header of the ESP32-S3-LCD-1.47B.'})
CREATE (esp32_gps_uart_plug:Connector {id: 'esp32_gps_uart_plug', name: 'ESP32 GPS UART 2-pin plug', type: '2-position housing', user_gender: 'female housing', positions: 2, nominal_pitch_mm: 2.54, notes: 'Plugs onto ESP32 left-header positions 7 and 8 (GP4, GP5), which are adjacent, and carries the GPS UART signal pair.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'primary', diagram_group: 'harness', diagram_order: 13})
CREATE (esp32_can_logic_plug:Connector {id: 'esp32_can_logic_plug', name: 'ESP32 CAN logic 2-pin plug', type: '2-position housing', user_gender: 'female housing', positions: 2, nominal_pitch_mm: 2.54, notes: 'Plugs onto ESP32 right-header positions 7 and 8 (GP9, GP8), which are adjacent, and carries the TWAI TX/RX leads to the SN65 4-pin plug.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'primary', diagram_group: 'harness', diagram_order: 14})
CREATE (lg290p_uart_cable_plug:Connector {id: 'lg290p_uart_cable_plug', name: 'LG290P UART cable plug', type: 'JST SH 1.0 mm 4-position housing', series: 'JST SH', positions: 4, nominal_pitch_mm: 1.0, user_gender: 'female housing', pin_order_status: 'not recorded; pins listed as 3.3V, GND, TX, RX without position numbers', identification: 'inferred: the Waveshare LG290P GNSS RTK Module brings its UART out on an SH1.0 4-pin connector and ships SH1.0 4-pin cables; confirm against the board in hand', notes: 'Harness end at the LG290P: a 1.0 mm pitch JST SH housing, a different series from the 2.54 mm housings at the ESP32 and SN65. Carries the GPS UART pair and the LG290P 3.3V/GND leads.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'primary', diagram_group: 'harness', diagram_order: 31})
CREATE (antenna_cable_plug:Connector {id: 'antenna_cable_plug', name: 'GNSS antenna cable plug', type: 'RF coaxial plug', connector_standard: 'not recorded', notes: 'Connector at the end of the antenna cable; mates with the LG290P antenna connector.', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'external_device', diagram_order: 64})
CREATE (host_usb_port:Connector {id: 'host_usb_port', variants: ['var_usb_pc'], name: 'PC USB port', device: 'host_pc', type: 'USB host receptacle', receptacle_type: 'not recorded', notes: 'USB port on the development PC (or USB supply) that the USB-C cable plugs into.'})

// Configurations. The logger is used in one configuration at a time; each variation point names
// the alternatives, and every element that exists only in some of them lists those in `variants`.
// Elements with no `variants` property are present in every configuration.
CREATE (vp_usb_c:VariationPoint {id: 'vp_usb_c', name: 'USB-C connection', default_variant: 'var_usb_power', notes: 'The same USB-C cable goes to the development PC while programming or debugging, and to a USB power source in use.'})
CREATE (var_usb_power:Variant {id: 'var_usb_power', name: 'In use: USB power source'})
CREATE (var_usb_pc:Variant {id: 'var_usb_pc', name: 'Programming and debugging: development PC'})
CREATE (vp_vehicle_bus:VariationPoint {id: 'vp_vehicle_bus', name: 'Vehicle CAN bus', default_variant: 'var_718_chassis', notes: 'The transceiver CAN pigtail takes one vehicle lead at a time, for one car and one bus, or is left free.'})
CREATE (var_718_chassis:Variant {id: 'var_718_chassis', name: 'Porsche 718 Chassis bus'})
CREATE (var_718_drive:Variant {id: 'var_718_drive', name: 'Porsche 718 Drive bus'})
CREATE (var_987_2_drive:Variant {id: 'var_987_2_drive', name: 'Porsche 987.2 Drive bus'})
CREATE (var_frs_obd:Variant {id: 'var_frs_obd', name: 'Scion FR-S CAN at the OBD-II port'})
CREATE (var_no_vehicle:Variant {id: 'var_no_vehicle', name: 'No vehicle attached'})

CREATE (usb_power_source:Device {id: 'usb_power_source', variants: ['var_usb_power'], name: 'USB power source', type: '5V USB supply', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'external_device', diagram_order: 6, notes: 'Powers the logger in use through the same USB-C cable; carries no data.'})
CREATE (usb_power_port:Connector {id: 'usb_power_port', variants: ['var_usb_power'], name: 'USB power source port', device: 'usb_power_source', type: 'USB receptacle', receptacle_type: 'not recorded'})
CREATE (usb_power_vbus:Pin {id: 'usb_power_vbus', variants: ['var_usb_power'], connector: 'usb_power_port', name: 'VBUS', type: 'power_out', voltage: '5V'})
CREATE (usb_power_gnd:Pin {id: 'usb_power_gnd', variants: ['var_usb_power'], connector: 'usb_power_port', name: 'GND', type: 'ground'})
CREATE (usb_power_dp:Pin {id: 'usb_power_dp', variants: ['var_usb_power'], connector: 'usb_power_port', name: 'D+', type: 'usb_data', notes: 'No data from a power source; how the supply terminates D+/D- is not recorded.'})
CREATE (usb_power_dn:Pin {id: 'usb_power_dn', variants: ['var_usb_power'], connector: 'usb_power_port', name: 'D-', type: 'usb_data', notes: 'No data from a power source; how the supply terminates D+/D- is not recorded.'})

CREATE (porsche_718_can_chassis:CANBus {id: 'porsche_718_can_chassis', variants: ['var_718_chassis'], name: 'Chassis CAN', vehicle_id: 'porsche_718', network_role: 'chassis CAN', tap_location: 'chassis CAN pair at the gateway; the VAG 20-pin gateway map places chassis CAN on pins 8/18, unconfirmed for the 718', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'vehicle_bus', diagram_order: 79})

CREATE (scion_frs:Vehicle {id: 'scion_frs', variants: ['var_frs_obd'], manufacturer: 'Scion', model: 'FR-S', name: 'Scion FR-S', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'vehicle', diagram_order: 92})
CREATE (scion_frs_can:CANBus {id: 'scion_frs_can', variants: ['var_frs_obd'], name: 'CAN at OBD-II port', vehicle_id: 'scion_frs', network_role: 'CAN available at the diagnostic connector', standard: 'ISO 15765-4 on SAE J1962 pins 6 (CAN-H) and 14 (CAN-L)', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'vehicle_bus', diagram_order: 82})
CREATE (frs_obd_port:Connector {id: 'frs_obd_port', variants: ['var_frs_obd'], name: 'FR-S OBD-II port', type: 'SAE J1962 16-position vehicle diagnostic connector', standard: 'SAE J1962', positions: 16, positions_in_use: [6, 14], user_gender: 'female', location: 'driver footwell, under the dash'})
CREATE (frs_obd_6:Pin {id: 'frs_obd_6', variants: ['var_frs_obd'], connector: 'frs_obd_port', name: 'CAN-H', pin_number: 6, signal: 'CAN-H', polarity: '+', type: 'can_diff_contact'})
CREATE (frs_obd_14:Pin {id: 'frs_obd_14', variants: ['var_frs_obd'], connector: 'frs_obd_port', name: 'CAN-L', pin_number: 14, signal: 'CAN-L', polarity: '-', type: 'can_diff_contact'})

CREATE (obd_can_lead:Harness {id: 'obd_can_lead', variants: ['var_frs_obd'], name: 'Removable OBD-II CAN lead', wires: 2, pinout: 'Dupont pin 1 CANL to OBD pin 14; Dupont pin 2 CANH to OBD pin 6', colors: 'not recorded', color_note: 'OBD-II breakout wire colours are not standardised; vendor charts differ (one gives pin 6 green, pin 14 brown/white).', enclosure_scope: 'external', notes: 'Used only on the Scion FR-S: a Dupont female housing for the transceiver CAN pigtail at one end and an OBD-II plug at the other. The Porsches use the PosiTap lead instead.'})
CREATE (obd_lead_socket:Connector {id: 'obd_lead_socket', variants: ['var_frs_obd'], name: 'OBD-II lead Dupont female housing', type: '2-position Dupont housing', series: 'Dupont', positions: 2, nominal_pitch_mm: 2.54, user_gender: 'female housing', mounting: 'on the removable OBD-II CAN lead', pin_1_signal: 'CANL', pin_2_signal: 'CANH', housing_status: 'assumed one 2-position housing; not recorded', notes: 'Takes the male Dupont pins of the transceiver CAN pigtail.'})
CREATE (obd_lead_pin1:Pin {id: 'obd_lead_pin1', variants: ['var_frs_obd'], connector: 'obd_lead_socket', name: 'Pin 1 CANL', pin_number: 1, signal: 'CAN-L', polarity: '-', type: 'can_diff_contact'})
CREATE (obd_lead_pin2:Pin {id: 'obd_lead_pin2', variants: ['var_frs_obd'], connector: 'obd_lead_socket', name: 'Pin 2 CANH', pin_number: 2, signal: 'CAN-H', polarity: '+', type: 'can_diff_contact'})
CREATE (obd_lead_plug:Connector {id: 'obd_lead_plug', variants: ['var_frs_obd'], name: 'OBD-II lead plug', type: 'SAE J1962 16-position plug', standard: 'SAE J1962', positions: 16, populated_positions: [6, 14], user_gender: 'male plug', notes: 'Only positions 6 (CAN-H) and 14 (CAN-L) are populated, per SAE J1962 / ISO 15765-4.'})
CREATE (obd_plug_6:Pin {id: 'obd_plug_6', variants: ['var_frs_obd'], connector: 'obd_lead_plug', name: 'CAN-H', pin_number: 6, signal: 'CAN-H', polarity: '+', type: 'can_diff_contact'})
CREATE (obd_plug_14:Pin {id: 'obd_plug_14', variants: ['var_frs_obd'], connector: 'obd_lead_plug', name: 'CAN-L', pin_number: 14, signal: 'CAN-L', polarity: '-', type: 'can_diff_contact'})

// Enclosure-boundary and external-interface model.
CREATE (rcx_enclosure:Enclosure {id: 'rcx_enclosure', name: 'RCX RTK Datalogger enclosure', type: '3D-printed electronics enclosure', diagram_level: 'primary', diagram_group: 'enclosure', diagram_order: 0, notes: 'Internal electronics are contained here. Externally accessible interfaces are USB-C (5V power and native USB data), the GNSS antenna connection, and the transceiver CAN pigtail, which leaves the enclosure from the SN65 parallel CAN header.'})
CREATE (lg290p_antenna_connector:Connector {id: 'lg290p_antenna_connector', name: 'LG290P antenna connector', device: 'lg290p', type: 'RF antenna connector', connector_standard: 'TBD from exact LG290P carrier/module', role: 'GNSS RF input', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', interface_exposure: 'external', external_interface: true, interface_type: 'gnss_antenna', cover_label: 'GNSS ANTENNA', cover_order: 20, diagram_level: 'primary', diagram_group: 'external_interface', diagram_order: 35, physical_position_status: 'connector location and standard not yet dimensioned', notes: 'Externally accessible antenna connection on the LG290P module.'})
CREATE (external_gnss_antenna:Antenna {id: 'external_gnss_antenna', name: 'External multiband GNSS antenna', type: 'active GNSS antenna', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'external_device', diagram_order: 65, mounting: 'vehicle exterior or other sky-view location', notes: 'The antenna cable is permanently attached at the antenna and ends in the antenna cable plug, which mates with the LG290P antenna connector.'})
CREATE (host_pc:Host {id: 'host_pc', variants: ['var_usb_pc'], name: 'Development PC running Arduino IDE', type: 'USB host', role: 'firmware upload and serial monitor over the ESP32-S3 USB Serial/JTAG port', connection: 'USB-C cable to the ESP32 onboard USB-C connector', attached: 'during development; in the vehicle the same port takes 5V from a USB supply', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'external_device', diagram_order: 5})
// Vehicle-specific CAN mappings. Vehicle wire colors belong to the tap-to-bus
// relationship, not globally to either the PosiTap or CAN bus node.
CREATE (porsche_718:Vehicle {id: 'porsche_718', variants: ['var_718_drive', 'var_718_chassis'], manufacturer: 'Porsche', model: '718', generation: '982', name: 'Porsche 718', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'vehicle', diagram_order: 90})
CREATE (porsche_987_2:Vehicle {id: 'porsche_987_2', variants: ['var_987_2_drive'], manufacturer: 'Porsche', model: '987.2', generation: '987.2', name: 'Porsche 987.2', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'vehicle', diagram_order: 91})
CREATE (porsche_718_can_drive_high:CANBus {id: 'porsche_718_can_drive_high', variants: ['var_718_drive'], name: 'Drive CAN', vehicle_id: 'porsche_718', network_role: 'drive/powertrain CAN', bitrate_kbps: 500, tap_location: 'drive CAN pair at the gateway harness (pin 16 = CAN-H per community reports)', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'vehicle_bus', diagram_order: 80})
CREATE (porsche_987_2_can_drive:CANBus {id: 'porsche_987_2_can_drive', variants: ['var_987_2_drive'], name: 'CAN Drive', vehicle_id: 'porsche_987_2', network_role: 'drive/powertrain CAN', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'vehicle_bus', diagram_order: 81})
CREATE (esp_5v:Pin {id: 'esp_5v', device: 'esp32', connector: 'esp32_header_left', name: '5V', type: 'power', direction: 'IN/OUT', voltage: '5V', header_side: 'left', header_order: 1, functions: ['5V rail']})
CREATE (esp_gnd_l:Pin {id: 'esp_gnd_l', device: 'esp32', connector: 'esp32_header_left', name: 'GND', type: 'ground', header_side: 'left', header_order: 2, functions: ['Ground']})
CREATE (esp_3v3:Pin {id: 'esp_3v3', device: 'esp32', connector: 'esp32_header_left', name: '3V3(OUT)', type: 'power_out', direction: 'OUT', voltage: '3.3V', header_side: 'left', header_order: 3, functions: ['3.3V regulated output']})
CREATE (esp_gp0:Pin {id: 'esp_gp0', device: 'esp32', connector: 'esp32_header_left', name: 'GP0', type: 'gpio', logic: '3.3V', header_side: 'left', header_order: 4, functions: ['UART', 'PWM', 'I2S', 'I2C', 'SPI', 'GPIO']})
CREATE (esp_gp2:Pin {id: 'esp_gp2', device: 'esp32', connector: 'esp32_header_left', name: 'GP2', type: 'gpio', logic: '3.3V', header_side: 'left', header_order: 5, functions: ['UART', 'PWM', 'I2S', 'ADC', 'I2C', 'SPI', 'GPIO']})
CREATE (esp_gp3:Pin {id: 'esp_gp3', device: 'esp32', connector: 'esp32_header_left', name: 'GP3', type: 'gpio', logic: '3.3V', header_side: 'left', header_order: 6, functions: ['UART', 'PWM', 'I2S', 'ADC', 'I2C', 'SPI', 'GPIO']})
CREATE (esp_gp4:Pin {id: 'esp_gp4', device: 'esp32', connector: 'esp32_header_left', name: 'GP4', type: 'gpio', logic: '3.3V', header_side: 'left', header_order: 7, functions: ['UART', 'PWM', 'I2S', 'ADC', 'I2C', 'SPI', 'GPIO', 'UART1_RX'], assigned_function: 'UART1_RX', direction: 'IN', notes: 'Receives LG290P TX'})
CREATE (esp_gp5:Pin {id: 'esp_gp5', device: 'esp32', connector: 'esp32_header_left', name: 'GP5', type: 'gpio', logic: '3.3V', header_side: 'left', header_order: 8, functions: ['UART', 'PWM', 'I2S', 'ADC', 'I2C', 'SPI', 'GPIO', 'UART1_TX'], assigned_function: 'UART1_TX', direction: 'OUT', notes: 'Transmits to LG290P RX'})
CREATE (esp_gp6:Pin {id: 'esp_gp6', device: 'esp32', connector: 'esp32_header_left', name: 'GP6', type: 'gpio', logic: '3.3V', header_side: 'left', header_order: 9, functions: ['UART', 'PWM', 'I2S', 'ADC', 'I2C', 'SPI', 'GPIO']})
CREATE (esp_txd0:Pin {id: 'esp_txd0', device: 'esp32', connector: 'esp32_header_right', name: 'TX', type: 'gpio', logic: '3.3V', header_side: 'right', header_order: 1, functions: ['UART0_TX'], assigned_function: 'USB/UART0 TX'})
CREATE (esp_rxd0:Pin {id: 'esp_rxd0', device: 'esp32', connector: 'esp32_header_right', name: 'RX', type: 'gpio', logic: '3.3V', header_side: 'right', header_order: 2, functions: ['UART0_RX'], assigned_function: 'USB/UART0 RX'})
CREATE (esp_vbat:Pin {id: 'esp_vbat', device: 'esp32', connector: 'esp32_header_right', name: 'VBAT', type: 'power', header_side: 'right', header_order: 3, functions: ['VBAT']})
CREATE (esp_gnd_r:Pin {id: 'esp_gnd_r', device: 'esp32', connector: 'esp32_header_right', name: 'GND', type: 'ground', header_side: 'right', header_order: 4, functions: ['Ground']})
CREATE (esp_gp11:Pin {id: 'esp_gp11', device: 'esp32', connector: 'esp32_header_right', name: 'GP11', type: 'gpio', logic: '3.3V', header_side: 'right', header_order: 5, functions: ['SPI', 'I2C', 'ADC', 'I2S', 'PWM', 'UART', 'GPIO']})
CREATE (esp_gp10:Pin {id: 'esp_gp10', device: 'esp32', connector: 'esp32_header_right', name: 'GP10', type: 'gpio', logic: '3.3V', header_side: 'right', header_order: 6, functions: ['SPI', 'I2C', 'ADC', 'I2S', 'PWM', 'UART', 'GPIO']})
CREATE (esp_gp9:Pin {id: 'esp_gp9', device: 'esp32', connector: 'esp32_header_right', name: 'GP9', type: 'gpio', logic: '3.3V', header_side: 'right', header_order: 7, functions: ['SPI', 'I2C', 'ADC', 'I2S', 'PWM', 'UART', 'GPIO', 'TWAI_TX'], assigned_function: 'TWAI_TX', direction: 'OUT', notes: 'Correct mapping: TWAI TX is GPIO9. Wired to SN65 TXD; typically listen-only.'})
CREATE (esp_gp8:Pin {id: 'esp_gp8', device: 'esp32', connector: 'esp32_header_right', name: 'GP8', type: 'gpio', logic: '3.3V', header_side: 'right', header_order: 8, functions: ['SPI', 'I2C', 'ADC', 'I2S', 'PWM', 'UART', 'GPIO', 'TWAI_RX'], assigned_function: 'TWAI_RX', direction: 'IN', notes: 'Correct mapping: TWAI RX is GPIO8. Receives SN65 RXD.'})
CREATE (esp_gp7:Pin {id: 'esp_gp7', device: 'esp32', connector: 'esp32_header_right', name: 'GP7', type: 'gpio', logic: '3.3V', header_side: 'right', header_order: 9, functions: ['SPI', 'I2C', 'ADC', 'I2S', 'PWM', 'UART', 'GPIO']})
CREATE (esp_io12:Pin {id: 'esp_io12', device: 'esp32', name: 'IO12', type: 'internal_gpio', functions: ['IMU_INT2', 'GPIO']})
CREATE (esp_io13:Pin {id: 'esp_io13', device: 'esp32', name: 'IO13', type: 'internal_gpio', functions: ['IMU_INT1']})
CREATE (esp_io14:Pin {id: 'esp_io14', device: 'esp32', name: 'IO14', type: 'internal_gpio', functions: ['SD_SCLK']})
CREATE (esp_io15:Pin {id: 'esp_io15', device: 'esp32', name: 'IO15', type: 'internal_gpio', functions: ['SD_MOSI']})
CREATE (esp_io16:Pin {id: 'esp_io16', device: 'esp32', name: 'IO16', type: 'internal_gpio', functions: ['SD_MISO']})
CREATE (esp_io17:Pin {id: 'esp_io17', device: 'esp32', name: 'IO17', type: 'internal_gpio', functions: ['SD_D2']})
CREATE (esp_io18:Pin {id: 'esp_io18', device: 'esp32', name: 'IO18', type: 'internal_gpio', functions: ['SD_D1']})
CREATE (esp_io19:Pin {id: 'esp_io19', device: 'esp32', name: 'IO19', type: 'internal_gpio', functions: ['USB_N'], assigned_function: 'USB_D-', notes: 'Native USB D-; on-board trace to the USB-C connector'})
CREATE (esp_io20:Pin {id: 'esp_io20', device: 'esp32', name: 'IO20', type: 'internal_gpio', functions: ['USB_P'], assigned_function: 'USB_D+', notes: 'Native USB D+; on-board trace to the USB-C connector'})
CREATE (esp_io21:Pin {id: 'esp_io21', device: 'esp32', name: 'IO21', type: 'internal_gpio', functions: ['SD_CS']})
CREATE (esp_io38:Pin {id: 'esp_io38', device: 'esp32', name: 'IO38', type: 'internal_gpio', functions: ['RGB_IO']})
CREATE (esp_io39:Pin {id: 'esp_io39', device: 'esp32', name: 'IO39', type: 'internal_gpio', functions: ['LCD_RST']})
CREATE (esp_io40:Pin {id: 'esp_io40', device: 'esp32', name: 'IO40', type: 'internal_gpio', functions: ['LCD_CLK']})
CREATE (esp_io41:Pin {id: 'esp_io41', device: 'esp32', name: 'IO41', type: 'internal_gpio', functions: ['LCD_DC']})
CREATE (esp_io42:Pin {id: 'esp_io42', device: 'esp32', name: 'IO42', type: 'internal_gpio', functions: ['LCD_CS']})
CREATE (esp_io43:Pin {id: 'esp_io43', device: 'esp32', name: 'IO43', type: 'internal_gpio', functions: ['UART0_TX']})
CREATE (esp_io44:Pin {id: 'esp_io44', device: 'esp32', name: 'IO44', type: 'internal_gpio', functions: ['UART0_RX']})
CREATE (esp_io45:Pin {id: 'esp_io45', device: 'esp32', name: 'IO45', type: 'internal_gpio', functions: ['LCD_DIN']})
CREATE (esp_io46:Pin {id: 'esp_io46', device: 'esp32', name: 'IO46', type: 'internal_gpio', functions: ['LCD_BL']})
CREATE (esp_io47:Pin {id: 'esp_io47', device: 'esp32', name: 'IO47', type: 'internal_gpio', functions: ['IMU_SCL']})
CREATE (esp_io48:Pin {id: 'esp_io48', device: 'esp32', name: 'IO48', type: 'internal_gpio', functions: ['IMU_SDA']})
CREATE (gps_vcc:Pin {id: 'gps_vcc', device: 'lg290p', connector: 'lg290p_uart_connector', name: '3.3V', type: 'power_in', voltage: '3.3V'})
CREATE (gps_gnd:Pin {id: 'gps_gnd', device: 'lg290p', connector: 'lg290p_uart_connector', name: 'GND', type: 'ground'})
CREATE (gps_tx:Pin {id: 'gps_tx', device: 'lg290p', connector: 'lg290p_uart_connector', name: 'TX', type: 'signal', direction: 'OUT', logic: '3.3V', notes: 'GNSS TX to ESP32 UART1_RX / GP4'})
CREATE (gps_rx:Pin {id: 'gps_rx', device: 'lg290p', connector: 'lg290p_uart_connector', name: 'RX', type: 'signal', direction: 'IN', logic: '3.3V', notes: 'GNSS RX from ESP32 UART1_TX / GP5'})
CREATE (can_vcc:Pin {id: 'can_vcc', device: 'sn65', connector: 'sn65_logic_power_connector', name: 'VCC', pin_number: 1, type: 'power_in', voltage: '3.3V', position_frame: 'sn65_component_side_xz_v1', position_x_mm: 6.4852, position_y_mm: 9.0156, physical_edge: 'logic-header end', notes: 'Top pin in component-side reference view.'})
CREATE (can_gnd:Pin {id: 'can_gnd', device: 'sn65', connector: 'sn65_logic_power_connector', name: 'GND', pin_number: 2, type: 'ground', position_frame: 'sn65_component_side_xz_v1', position_x_mm: 6.4852, position_y_mm: 6.4956, physical_edge: 'logic-header end'})
CREATE (can_rxd:Pin {id: 'can_rxd', device: 'sn65', connector: 'sn65_logic_power_connector', name: 'RXD', pin_number: 3, type: 'signal', direction: 'OUT', logic: '3.3V', position_frame: 'sn65_component_side_xz_v1', position_x_mm: 6.4852, position_y_mm: 3.9756, physical_edge: 'logic-header end', notes: 'CAN logic receive data to ESP32 GPIO8/TWAI_RX'})
CREATE (can_txd:Pin {id: 'can_txd', device: 'sn65', connector: 'sn65_logic_power_connector', name: 'TXD', pin_number: 4, type: 'signal', direction: 'IN', logic: '3.3V', position_frame: 'sn65_component_side_xz_v1', position_x_mm: 6.4852, position_y_mm: 1.4556, physical_edge: 'logic-header end', notes: 'CAN logic transmit data from ESP32 GPIO9/TWAI_TX; may remain undriven in listen-only mode'})
CREATE (can_h:Pin {id: 'can_h', device: 'sn65', name: 'CANH logical signal', type: 'can_diff', direction: 'BIDIR', logical_signal: true, physical_contacts: 2, notes: 'CAN differential high is exposed at the screw terminal and a parallel header pin.'})
CREATE (can_l:Pin {id: 'can_l', device: 'sn65', name: 'CANL logical signal', type: 'can_diff', direction: 'BIDIR', logical_signal: true, physical_contacts: 2, notes: 'CAN differential low is exposed at the screw terminal and a parallel header pin.'})
CREATE (can_l_screw:Pin {id: 'can_l_screw', device: 'sn65', connector: 'sn65_can_screw_terminal', name: 'CANL screw terminal', display_position: 1, signal: 'CAN-L', polarity: '-', type: 'can_diff_contact', preferred_connection: false, position_frame: 'sn65_component_side_xz_v1', position_x_mm: 28.4820, position_y_mm: 7.9591, notes: 'Upper screw terminal in component-side reference view.'})
CREATE (can_h_screw:Pin {id: 'can_h_screw', device: 'sn65', connector: 'sn65_can_screw_terminal', name: 'CANH screw terminal', display_position: 2, signal: 'CAN-H', polarity: '+', type: 'can_diff_contact', preferred_connection: false, position_frame: 'sn65_component_side_xz_v1', position_x_mm: 28.4820, position_y_mm: 3.2200, notes: 'Lower screw terminal in component-side reference view.'})
CREATE (can_l_pad:Pin {id: 'can_l_pad', device: 'sn65', connector: 'sn65_can_parallel_pads', name: 'CANL parallel header pin', display_position: 1, signal: 'CAN-L', polarity: '-', type: 'can_diff_contact', preferred_connection: true, position_frame: 'sn65_component_side_xz_v1', position_x_mm: 22.5881, position_y_mm: 6.5008, notes: 'Electrically parallel with CANL screw terminal.'})
CREATE (can_h_pad:Pin {id: 'can_h_pad', device: 'sn65', connector: 'sn65_can_parallel_pads', name: 'CANH parallel header pin', display_position: 2, signal: 'CAN-H', polarity: '+', type: 'can_diff_contact', preferred_connection: true, position_frame: 'sn65_component_side_xz_v1', position_x_mm: 22.5881, position_y_mm: 3.9808, notes: 'Electrically parallel with CANH screw terminal.'})
CREATE (can_pigtail_socket_pin1:Pin {id: 'can_pigtail_socket_pin1', connector: 'can_pigtail_socket', name: 'Pin 1 CANL', pin_number: 1, signal: 'CAN-L', polarity: '-', type: 'can_diff_contact'})
CREATE (can_pigtail_plug_pin1:Pin {id: 'can_pigtail_plug_pin1', connector: 'can_pigtail_plug', name: 'Pin 1 CANL', pin_number: 1, signal: 'CAN-L', polarity: '-', type: 'can_diff_contact'})
CREATE (can_pigtail_socket_pin2:Pin {id: 'can_pigtail_socket_pin2', connector: 'can_pigtail_socket', name: 'Pin 2 CANH', pin_number: 2, signal: 'CAN-H', polarity: '+', type: 'can_diff_contact'})
CREATE (can_pigtail_plug_pin2:Pin {id: 'can_pigtail_plug_pin2', connector: 'can_pigtail_plug', name: 'Pin 2 CANH', pin_number: 2, signal: 'CAN-H', polarity: '+', type: 'can_diff_contact'})
CREATE (positap_lead_pin1:Pin {id: 'positap_lead_pin1', variants: ['var_718_drive', 'var_718_chassis', 'var_987_2_drive'], connector: 'positap_lead_socket', name: 'Pin 1 CANL', pin_number: 1, signal: 'CAN-L', polarity: '-', type: 'can_diff_contact', wire_color: 'green'})
CREATE (positap_lead_pin2:Pin {id: 'positap_lead_pin2', variants: ['var_718_drive', 'var_718_chassis', 'var_987_2_drive'], connector: 'positap_lead_socket', name: 'Pin 2 CANH', pin_number: 2, signal: 'CAN-H', polarity: '+', type: 'can_diff_contact', wire_color: 'white'})
CREATE (usb_c_cable:Harness {id: 'usb_c_cable', name: 'USB-C cable', type: 'jacketed cable', jacketed: true, wires: 4, conductors: ['VBUS', 'GND', 'D+', 'D-'], notes: 'One jacketed cable from the development PC (or a USB supply) to the ESP32 onboard USB-C receptacle. Its four conductors run together in the same jacket and carry 5V power and native USB data.'})
CREATE (gps_uart:Harness {id: 'gps_uart', name: 'GPS UART signal pair', wires: 2, colors: 'orange, yellow', notes: 'UART signal wires from the LG290P UART cable plug (JST SH) to the ESP32 GPS UART 2-pin plug on header positions 7 and 8.'})
CREATE (can_logic_power:Harness {id: 'can_logic_power', name: 'CAN logic/power 4-pin harness', wires: 4, colors: 'red, black, green, blue', notes: 'Four leads from the SN65 4-pin plug: VCC and GND to the 3V3 and GND positions of the ESP32 3-pin power plug, RXD and TXD to GP8 and GP9 through the ESP32 CAN logic 2-pin plug.'})
CREATE (gps_power:Harness {id: 'gps_power', name: 'GPS power pair', wires: 2, colors: 'red, black', notes: 'LG290P 3.3V and GND leads from the LG290P UART cable plug, doubled into the VCC and GND positions of the SN65 4-pin plug.'})
CREATE (fan_leads:Harness {id: 'fan_leads', name: 'Fan leads', wires: 2, colors: 'red, black', notes: 'Fan +5V and GND into the 5V and GND positions of the ESP32 3-pin power plug.'})
CREATE (can_pigtail:Harness {id: 'can_pigtail', name: 'Transceiver CAN pigtail', wires: 2, colors: 'not recorded', pinout: 'pin 1 CANL; pin 2 CANH at both ends', notes: 'Female Dupont housing on the SN65 parallel CAN header at one end, male Dupont pins at the other. Every vehicle lead plugs onto its male end.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal to external', diagram_level: 'detail'})
CREATE (vehicle_can_taps:Harness {id: 'vehicle_can_taps', variants: ['var_718_drive', 'var_718_chassis', 'var_987_2_drive'], name: 'Removable CAN tap lead', wires: 2, colors: 'white, green', pinout: 'pin 1 CANL green; pin 2 CANH white', notes: 'Runs from its Dupont female housing, plugged onto the transceiver CAN pigtail, to the PosiTap connectors. Vehicle-side conductor colors are defined per vehicle on TAPS_VEHICLE_CAN relationships.', enclosure_scope: 'external', diagram_level: 'detail'})
CREATE (function_UART:Function {name: 'UART', id: 'function:UART'})
CREATE (function_PWM:Function {name: 'PWM', id: 'function:PWM'})
CREATE (function_I2S:Function {name: 'I2S', id: 'function:I2S'})
CREATE (function_ADC:Function {name: 'ADC', id: 'function:ADC'})
CREATE (function_I2C:Function {name: 'I2C', id: 'function:I2C'})
CREATE (function_SPI:Function {name: 'SPI', id: 'function:SPI'})
CREATE (function_GPIO:Function {name: 'GPIO', id: 'function:GPIO'})
CREATE (function_UART1_RX:Function {name: 'UART1_RX', id: 'function:UART1_RX'})
CREATE (function_UART1_TX:Function {name: 'UART1_TX', id: 'function:UART1_TX'})
CREATE (function_TWAI_RX:Function {name: 'TWAI_RX', id: 'function:TWAI_RX'})
CREATE (function_TWAI_TX:Function {name: 'TWAI_TX', id: 'function:TWAI_TX'})
CREATE (function_UART0_TX:Function {name: 'UART0_TX', id: 'function:UART0_TX'})
CREATE (function_UART0_RX:Function {name: 'UART0_RX', id: 'function:UART0_RX'})
CREATE (function_SD_SCLK:Function {name: 'SD_SCLK', id: 'function:SD_SCLK'})
CREATE (function_SD_MOSI:Function {name: 'SD_MOSI', id: 'function:SD_MOSI'})
CREATE (function_SD_MISO:Function {name: 'SD_MISO', id: 'function:SD_MISO'})
CREATE (function_SD_D2:Function {name: 'SD_D2', id: 'function:SD_D2'})
CREATE (function_SD_D1:Function {name: 'SD_D1', id: 'function:SD_D1'})
CREATE (function_SD_CS:Function {name: 'SD_CS', id: 'function:SD_CS'})
CREATE (function_RGB_IO:Function {name: 'RGB_IO', id: 'function:RGB_IO'})
CREATE (function_LCD_RST:Function {name: 'LCD_RST', id: 'function:LCD_RST'})
CREATE (function_LCD_CLK:Function {name: 'LCD_CLK', id: 'function:LCD_CLK'})
CREATE (function_LCD_DC:Function {name: 'LCD_DC', id: 'function:LCD_DC'})
CREATE (function_LCD_CS:Function {name: 'LCD_CS', id: 'function:LCD_CS'})
CREATE (function_LCD_DIN:Function {name: 'LCD_DIN', id: 'function:LCD_DIN'})
CREATE (function_LCD_BL:Function {name: 'LCD_BL', id: 'function:LCD_BL'})
CREATE (function_IMU_INT2:Function {name: 'IMU_INT2', id: 'function:IMU_INT2'})
CREATE (function_IMU_INT1:Function {name: 'IMU_INT1', id: 'function:IMU_INT1'})
CREATE (function_IMU_SCL:Function {name: 'IMU_SCL', id: 'function:IMU_SCL'})
CREATE (function_IMU_SDA:Function {name: 'IMU_SDA', id: 'function:IMU_SDA'})
CREATE (function_BAT_ADC:Function {name: 'BAT_ADC', id: 'function:BAT_ADC'})
CREATE (function_VBAT:Function {name: 'VBAT', id: 'function:VBAT'})
CREATE (function_Ground:Function {name: 'Ground', id: 'function:Ground'})
CREATE (function_3_3V_regulated_output:Function {name: '3.3V regulated output', id: 'function:3.3V regulated output'})
CREATE (function_5V_rail:Function {name: '5V rail', id: 'function:5V rail'})
CREATE (function_USB_UART0_TX:Function {name: 'USB/UART0 TX', id: 'function:USB/UART0 TX'})
CREATE (function_USB_UART0_RX:Function {name: 'USB/UART0 RX', id: 'function:USB/UART0 RX'})
CREATE (function_USB_N:Function {name: 'USB_N', id: 'function:USB_N'})
CREATE (function_USB_P:Function {name: 'USB_P', id: 'function:USB_P'})
CREATE (esp32_usb_vbus:Pin {id: 'esp32_usb_vbus', device: 'esp32', connector: 'esp32_usb_c', name: 'USBC 5VBUS', type: 'power_in', direction: 'IN', voltage: '5V', notes: 'VBUS pin internal to the ESP32 onboard USB-C receptacle; feeds the board 5V rail.'})
CREATE (esp32_usb_gnd:Pin {id: 'esp32_usb_gnd', device: 'esp32', connector: 'esp32_usb_c', name: 'USB-C GND', type: 'ground', notes: 'Ground pin internal to the ESP32 onboard USB-C receptacle; common with board ground.'})
CREATE (esp32_usb_dn:Pin {id: 'esp32_usb_dn', device: 'esp32', connector: 'esp32_usb_c', name: 'USB D-', type: 'usb_data', direction: 'BIDIR', notes: 'D- contacts of the ESP32 onboard USB-C receptacle; routed on-board to GPIO19.'})
CREATE (esp32_usb_dp:Pin {id: 'esp32_usb_dp', device: 'esp32', connector: 'esp32_usb_c', name: 'USB D+', type: 'usb_data', direction: 'BIDIR', notes: 'D+ contacts of the ESP32 onboard USB-C receptacle; routed on-board to GPIO20.'})
CREATE (fan_vplus:Pin {id: 'fan_vplus', device: 'fan', name: '+5V', type: 'power_in', direction: 'IN', voltage: '5V', lead_color: 'red', termination: 'flying lead; no connector at the fan'})
CREATE (fan_gnd:Pin {id: 'fan_gnd', device: 'fan', name: 'GND', type: 'ground', lead_color: 'black', termination: 'flying lead; no connector at the fan'})
CREATE (esp_uplug_rx:Pin {id: 'esp_uplug_rx', connector: 'esp32_gps_uart_plug', name: 'UART1 RX', pin_number: 1, type: 'signal', logic: '3.3V'})
CREATE (esp_uplug_tx:Pin {id: 'esp_uplug_tx', connector: 'esp32_gps_uart_plug', name: 'UART1 TX', pin_number: 2, type: 'signal', logic: '3.3V'})
CREATE (esp_cplug_tx:Pin {id: 'esp_cplug_tx', connector: 'esp32_can_logic_plug', name: 'TWAI TX', pin_number: 1, type: 'signal', logic: '3.3V'})
CREATE (esp_cplug_rx:Pin {id: 'esp_cplug_rx', connector: 'esp32_can_logic_plug', name: 'TWAI RX', pin_number: 2, type: 'signal', logic: '3.3V'})
CREATE (gps_plug_vcc:Pin {id: 'gps_plug_vcc', connector: 'lg290p_uart_cable_plug', name: '3.3V', type: 'power', voltage: '3.3V'})
CREATE (gps_plug_gnd:Pin {id: 'gps_plug_gnd', connector: 'lg290p_uart_cable_plug', name: 'GND', type: 'ground'})
CREATE (gps_plug_tx:Pin {id: 'gps_plug_tx', connector: 'lg290p_uart_cable_plug', name: 'TX', type: 'signal', logic: '3.3V'})
CREATE (gps_plug_rx:Pin {id: 'gps_plug_rx', connector: 'lg290p_uart_cable_plug', name: 'RX', type: 'signal', logic: '3.3V'})
CREATE (gps_rf_in:Pin {id: 'gps_rf_in', device: 'lg290p', connector: 'lg290p_antenna_connector', name: 'RF IN', type: 'rf', signal: 'GNSS RF'})
CREATE (antenna_plug_rf:Pin {id: 'antenna_plug_rf', connector: 'antenna_cable_plug', name: 'RF', type: 'rf', signal: 'GNSS RF'})
CREATE (antenna_rf_out:Pin {id: 'antenna_rf_out', device: 'external_gnss_antenna', name: 'RF OUT', type: 'rf', signal: 'GNSS RF', termination: 'flying lead; the antenna cable is permanently attached at the antenna'})
CREATE (host_usb_vbus:Pin {id: 'host_usb_vbus', variants: ['var_usb_pc'], connector: 'host_usb_port', name: 'VBUS', type: 'power_out', voltage: '5V'})
CREATE (host_usb_gnd:Pin {id: 'host_usb_gnd', variants: ['var_usb_pc'], connector: 'host_usb_port', name: 'GND', type: 'ground'})
CREATE (host_usb_dp:Pin {id: 'host_usb_dp', variants: ['var_usb_pc'], connector: 'host_usb_port', name: 'D+', type: 'usb_data', direction: 'BIDIR'})
CREATE (host_usb_dn:Pin {id: 'host_usb_dn', variants: ['var_usb_pc'], connector: 'host_usb_port', name: 'D-', type: 'usb_data', direction: 'BIDIR'})
CREATE (can_plug_vcc:Pin {id: 'can_plug_vcc', connector: 'can_logic_power_plug', name: 'VCC', pin_number: 1, type: 'power', voltage: '3.3V', termination: 'two wires: LG290P 3.3V lead and ESP32 3.3V lead'})
CREATE (can_plug_gnd:Pin {id: 'can_plug_gnd', connector: 'can_logic_power_plug', name: 'GND', pin_number: 2, type: 'ground', termination: 'two wires: LG290P GND lead and ESP32 GND lead'})
CREATE (can_plug_rxd:Pin {id: 'can_plug_rxd', connector: 'can_logic_power_plug', name: 'RXD', pin_number: 3, type: 'signal', logic: '3.3V'})
CREATE (can_plug_txd:Pin {id: 'can_plug_txd', connector: 'can_logic_power_plug', name: 'TXD', pin_number: 4, type: 'signal', logic: '3.3V'})
CREATE (esp_plug_5v:Pin {id: 'esp_plug_5v', connector: 'esp32_power_plug', name: '5V', pin_number: 1, type: 'power', voltage: '5V'})
CREATE (esp_plug_gnd:Pin {id: 'esp_plug_gnd', connector: 'esp32_power_plug', name: 'GND', pin_number: 2, type: 'ground', termination: 'two wires: SN65 plug ground lead and fan ground'})
CREATE (esp_plug_3v3:Pin {id: 'esp_plug_3v3', connector: 'esp32_power_plug', name: '3V3', pin_number: 3, type: 'power', voltage: '3.3V'})

MATCH (a {id: 'esp32'}), (b {id: 'esp32_usb_c'}) CREATE (a)-[:HAS_CONNECTOR {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_5v'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gnd_l'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_3v3'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp0'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp2'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp3'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp4'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp5'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp6'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_txd0'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_rxd0'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_vbat'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gnd_r'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp11'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp10'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp9'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp8'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp7'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io12'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io13'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io14'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io15'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io16'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io17'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io18'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io19'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io20'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io21'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io38'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io39'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io40'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io41'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io42'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io43'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io44'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io45'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io46'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io47'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io48'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p'}), (b {id: 'lg290p_uart_connector'}) CREATE (a)-[:HAS_CONNECTOR {}]->(b)
MATCH (a {id: 'lg290p'}), (b {id: 'gps_vcc'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p'}), (b {id: 'gps_gnd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p'}), (b {id: 'gps_tx'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p'}), (b {id: 'gps_rx'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'sn65_logic_power_connector'}) CREATE (a)-[:HAS_CONNECTOR {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'sn65_can_screw_terminal'}) CREATE (a)-[:HAS_CONNECTOR {preferred: false}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'sn65_can_parallel_pads'}) CREATE (a)-[:HAS_CONNECTOR {preferred: true}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'sn65_component_side_xz_v1'}) CREATE (a)-[:HAS_COORDINATE_FRAME {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_vcc'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_gnd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_rxd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_txd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_h'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_l'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_l_screw'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_h_screw'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_l_pad'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_h_pad'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65_logic_power_connector'}), (b {id: 'can_vcc'}) CREATE (a)-[:HAS_PIN {position: 1}]->(b)
MATCH (a {id: 'sn65_logic_power_connector'}), (b {id: 'can_gnd'}) CREATE (a)-[:HAS_PIN {position: 2}]->(b)
MATCH (a {id: 'sn65_logic_power_connector'}), (b {id: 'can_rxd'}) CREATE (a)-[:HAS_PIN {position: 3}]->(b)
MATCH (a {id: 'sn65_logic_power_connector'}), (b {id: 'can_txd'}) CREATE (a)-[:HAS_PIN {position: 4}]->(b)
MATCH (a {id: 'sn65_can_screw_terminal'}), (b {id: 'can_l_screw'}) CREATE (a)-[:HAS_PIN {display_position: 1}]->(b)
MATCH (a {id: 'sn65_can_screw_terminal'}), (b {id: 'can_h_screw'}) CREATE (a)-[:HAS_PIN {display_position: 2}]->(b)
MATCH (a {id: 'sn65_can_parallel_pads'}), (b {id: 'can_l_pad'}) CREATE (a)-[:HAS_PIN {display_position: 1}]->(b)
MATCH (a {id: 'sn65_can_parallel_pads'}), (b {id: 'can_h_pad'}) CREATE (a)-[:HAS_PIN {display_position: 2}]->(b)
MATCH (a {id: 'can_pigtail_socket'}), (b {id: 'can_pigtail_socket_pin1'}) CREATE (a)-[:HAS_PIN {position: 1}]->(b)
MATCH (a {id: 'can_pigtail_plug'}), (b {id: 'can_pigtail_plug_pin1'}) CREATE (a)-[:HAS_PIN {position: 1}]->(b)
MATCH (a {id: 'can_pigtail_socket'}), (b {id: 'can_pigtail_socket_pin2'}) CREATE (a)-[:HAS_PIN {position: 2}]->(b)
MATCH (a {id: 'can_pigtail_plug'}), (b {id: 'can_pigtail_plug_pin2'}) CREATE (a)-[:HAS_PIN {position: 2}]->(b)
MATCH (a {id: 'positap_lead_socket'}), (b {id: 'positap_lead_pin1'}) CREATE (a)-[:HAS_PIN {position: 1}]->(b)
MATCH (a {id: 'positap_lead_socket'}), (b {id: 'positap_lead_pin2'}) CREATE (a)-[:HAS_PIN {position: 2}]->(b)
MATCH (a {id: 'can_l_screw'}), (b {id: 'can_l'}) CREATE (a)-[:ELECTRICALLY_COMMON {signal: 'CAN-L'}]->(b)
MATCH (a {id: 'can_l_pad'}), (b {id: 'can_l'}) CREATE (a)-[:ELECTRICALLY_COMMON {signal: 'CAN-L'}]->(b)
MATCH (a {id: 'can_h_screw'}), (b {id: 'can_h'}) CREATE (a)-[:ELECTRICALLY_COMMON {signal: 'CAN-H'}]->(b)
MATCH (a {id: 'can_h_pad'}), (b {id: 'can_h'}) CREATE (a)-[:ELECTRICALLY_COMMON {signal: 'CAN-H'}]->(b)
MATCH (a {id: 'can_l_pad'}), (b {id: 'can_l_screw'}) CREATE (a)-[:PARALLEL_CONTACT {signal: 'CAN-L', preferred_contact: 'can_l_pad'}]->(b)
MATCH (a {id: 'can_h_pad'}), (b {id: 'can_h_screw'}) CREATE (a)-[:PARALLEL_CONTACT {signal: 'CAN-H', preferred_contact: 'can_h_pad'}]->(b)
MATCH (a {id: 'gps_plug_vcc'}), (b {id: 'can_plug_vcc'}) CREATE (a)-[:WIRE {id: 'w_gps_vcc_to_can_plug_vcc', color: 'red', signal: '3.3V', harness: 'gps_power', physical: 'LG290P UART cable plug 3.3V to SN65 4-pin plug VCC, doubled with w_can_plug_vcc_to_esp_plug_3v3'}]->(b)
MATCH (a {id: 'gps_plug_gnd'}), (b {id: 'can_plug_gnd'}) CREATE (a)-[:WIRE {id: 'w_gps_gnd_to_can_plug_gnd', color: 'black', signal: 'GND', harness: 'gps_power', physical: 'LG290P UART cable plug GND to SN65 4-pin plug GND, doubled with w_can_plug_gnd_to_esp_plug_gnd'}]->(b)
MATCH (a {id: 'esp_plug_3v3'}), (b {id: 'can_plug_vcc'}) CREATE (a)-[:WIRE {id: 'w_can_plug_vcc_to_esp_plug_3v3', color: 'red', signal: '3.3V', harness: 'can_logic_power', physical: 'ESP32 3-pin power plug 3V3 to SN65 4-pin plug VCC'}]->(b)
MATCH (a {id: 'esp_plug_gnd'}), (b {id: 'can_plug_gnd'}) CREATE (a)-[:WIRE {id: 'w_can_plug_gnd_to_esp_plug_gnd', color: 'black', signal: 'GND', harness: 'can_logic_power', physical: 'ESP32 3-pin power plug GND to SN65 4-pin plug GND, doubled at the ESP32 end with w_esp_plug_gnd_to_fan_gnd'}]->(b)
MATCH (a {id: 'esp_plug_5v'}), (b {id: 'fan_vplus'}) CREATE (a)-[:WIRE {id: 'w_esp_plug_5v_to_fan', color: 'red', signal: '5V', harness: 'fan_leads', physical: 'ESP32 3-pin power plug 5V to fan +5V lead'}]->(b)
MATCH (a {id: 'esp_plug_gnd'}), (b {id: 'fan_gnd'}) CREATE (a)-[:WIRE {id: 'w_esp_plug_gnd_to_fan_gnd', color: 'black', signal: 'GND', harness: 'fan_leads', physical: 'ESP32 3-pin power plug GND to fan GND lead, doubled with w_can_plug_gnd_to_esp_plug_gnd'}]->(b)
MATCH (a {id: 'gps_plug_tx'}), (b {id: 'esp_uplug_rx'}) CREATE (a)-[:WIRE {id: 'w_gps_tx_to_esp_gp4', color: 'orange', signal: 'LG290P_TX_TO_ESP32_UART1_RX', gauge: '26 AWG', harness: 'gps_uart', baud: 460800, physical: 'LG290P UART cable plug TX to ESP32 GPS UART plug position 1 (GP4)'}]->(b)
MATCH (a {id: 'esp_uplug_tx'}), (b {id: 'gps_plug_rx'}) CREATE (a)-[:WIRE {id: 'w_esp_gp5_to_gps_rx', color: 'yellow', signal: 'ESP32_UART1_TX_TO_LG290P_RX', gauge: '26 AWG', harness: 'gps_uart', baud: 460800, physical: 'ESP32 GPS UART plug position 2 (GP5) to LG290P UART cable plug RX'}]->(b)
MATCH (a {id: 'can_plug_rxd'}), (b {id: 'esp_cplug_rx'}) CREATE (a)-[:WIRE {id: 'w_can_rxd_to_esp_gp8', color: 'green', signal: 'SN65_RXD_TO_ESP32_TWAI_RX', gauge: '26 AWG', harness: 'can_logic_power', physical: 'SN65 4-pin plug RXD to ESP32 CAN logic plug position 2 (GP8)', notes: 'Correct mapping: GPIO8 = TWAI_RX'}]->(b)
MATCH (a {id: 'esp_cplug_tx'}), (b {id: 'can_plug_txd'}) CREATE (a)-[:WIRE {id: 'w_esp_gp9_to_can_txd', color: 'blue', signal: 'ESP32_TWAI_TX_TO_SN65_TXD', gauge: '26 AWG', harness: 'can_logic_power', physical: 'ESP32 CAN logic plug position 1 (GP9) to SN65 4-pin plug TXD', notes: 'Correct mapping: GPIO9 = TWAI_TX; may be configured listen-only and never driven'}]->(b)
MATCH (a {id: 'can_pigtail_socket'}), (b {id: 'sn65_can_parallel_pads'}) CREATE (a)-[:MATES_WITH {series: 'Dupont', positions: 2, detachable: true}]->(b)
MATCH (a {id: 'can_pigtail_socket_pin1'}), (b {id: 'can_l_pad'}) CREATE (a)-[:MATES_WITH {position: 1, signal: 'CAN-L'}]->(b)
MATCH (a {id: 'can_pigtail_socket_pin1'}), (b {id: 'can_pigtail_plug_pin1'}) CREATE (a)-[:WIRE {id: 'w_can_pigtail_canl', signal: 'CAN-L', polarity: '-', harness: 'can_pigtail', notes: 'Transceiver CAN pigtail: female housing pin 1 to male pin 1. Colour not recorded.'}]->(b)
MATCH (a {id: 'can_pigtail_socket_pin2'}), (b {id: 'can_h_pad'}) CREATE (a)-[:MATES_WITH {position: 2, signal: 'CAN-H'}]->(b)
MATCH (a {id: 'can_pigtail_socket_pin2'}), (b {id: 'can_pigtail_plug_pin2'}) CREATE (a)-[:WIRE {id: 'w_can_pigtail_canh', signal: 'CAN-H', polarity: '+', harness: 'can_pigtail', notes: 'Transceiver CAN pigtail: female housing pin 2 to male pin 2. Colour not recorded.'}]->(b)
MATCH (a {id: 'positap_lead_socket'}), (b {id: 'can_pigtail_plug'}) CREATE (a)-[:MATES_WITH {series: 'Dupont', positions: 2, detachable: true}]->(b)
MATCH (a {id: 'positap_lead_pin1'}), (b {id: 'can_pigtail_plug_pin1'}) CREATE (a)-[:MATES_WITH {position: 1, signal: 'CAN-L'}]->(b)
MATCH (a {id: 'positap_lead_pin2'}), (b {id: 'can_pigtail_plug_pin2'}) CREATE (a)-[:MATES_WITH {position: 2, signal: 'CAN-H'}]->(b)
MATCH (a {id: 'positap_lead_pin1'}), (b {id: 'positap_can_l'}) CREATE (a)-[:WIRE {id: 'w_positap_lead_pin1_to_positap_can_l', color: 'green', color_code: 'GRN', signal: 'CAN-L', polarity: '-', gauge: '22 AWG', harness: 'vehicle_can_taps', notes: 'Removable PosiTap lead from Dupont pin 1 to the CAN-L PosiTap.'}]->(b)
MATCH (a {id: 'positap_lead_pin2'}), (b {id: 'positap_can_h'}) CREATE (a)-[:WIRE {id: 'w_positap_lead_pin2_to_positap_can_h', color: 'white', color_code: 'WHT', signal: 'CAN-H', polarity: '+', gauge: '22 AWG', harness: 'vehicle_can_taps', notes: 'Removable PosiTap lead from Dupont pin 2 to the CAN-H PosiTap.'}]->(b)


// Enclosure membership and exposed interfaces.
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'esp32'}) CREATE (a)-[:CONTAINS {}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'lg290p'}) CREATE (a)-[:CONTAINS {}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'sn65'}) CREATE (a)-[:CONTAINS {}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'fan'}) CREATE (a)-[:CONTAINS {}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'esp32_power_plug'}) CREATE (a)-[:CONTAINS {}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'can_logic_power_plug'}) CREATE (a)-[:CONTAINS {}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'can_pigtail_socket'}) CREATE (a)-[:CONTAINS {}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'esp32_usb_c'}) CREATE (a)-[:EXPOSES_INTERFACE {interface_type: 'power_usb', cover_order: 10}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'lg290p_antenna_connector'}) CREATE (a)-[:EXPOSES_INTERFACE {interface_type: 'gnss_antenna', cover_order: 20}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'can_pigtail_socket'}) CREATE (a)-[:EXPOSES_INTERFACE {interface_type: 'vehicle_can', cover_order: 30}]->(b)
MATCH (a {id: 'lg290p'}), (b {id: 'lg290p_antenna_connector'}) CREATE (a)-[:HAS_CONNECTOR {role: 'GNSS RF input'}]->(b)
MATCH (a {id: 'antenna_rf_out'}), (b {id: 'antenna_plug_rf'}) CREATE (a)-[:RF_CABLE {signal: 'GNSS RF', direction: 'antenna to receiver', cable_location: 'external', notes: 'Antenna cable, permanently attached at the antenna and ending in the antenna cable plug.'}]->(b)

MATCH (a {id: 'porsche_718'}), (b {id: 'porsche_718_can_drive_high'}) CREATE (a)-[:HAS_CAN_BUS {}]->(b)
MATCH (a {id: 'porsche_987_2'}), (b {id: 'porsche_987_2_can_drive'}) CREATE (a)-[:HAS_CAN_BUS {}]->(b)

MATCH (a {id: 'positap_can_h'}), (b {id: 'porsche_718_can_drive_high'}) CREATE (a)-[:TAPS_VEHICLE_CAN {vehicle_id: 'porsche_718', bus_name: 'Drive CAN', signal: 'CAN-H', polarity: '+', vehicle_wire_color: 'ORG/BLK', vehicle_wire_color_full: 'orange/black', color_status: 'confirmed by two sources; one differs in base colour', color_source: 'Racelogic VBOX vehicle CAN database, Porsche 718 Cayman GT4 (982): CAN High orange/black; also the VAG standard powertrain CAN-High colour. planetkris (2018 Cayman, at gateway pin 16) gives brown/black, so check the base colour at the tap point.'}]->(b)
MATCH (a {id: 'positap_can_l'}), (b {id: 'porsche_718_can_drive_high'}) CREATE (a)-[:TAPS_VEHICLE_CAN {vehicle_id: 'porsche_718', bus_name: 'Drive CAN', signal: 'CAN-L', polarity: '-', vehicle_wire_color: 'ORG/BRN', vehicle_wire_color_full: 'orange/brown', color_status: 'confirmed by two sources; one differs in base colour', color_source: 'Racelogic VBOX vehicle CAN database, Porsche 718 Cayman GT4 (982): CAN Low orange/brown; VAG standard: every CAN-Low is orange/brown. planetkris (2018 Cayman, at the gateway) gives brown/brown.'}]->(b)
MATCH (a {id: 'positap_can_h'}), (b {id: 'porsche_987_2_can_drive'}) CREATE (a)-[:TAPS_VEHICLE_CAN {vehicle_id: 'porsche_987_2', bus_name: 'CAN Drive', signal: 'CAN-H', polarity: '+', vehicle_wire_color: 'YEL/WHT', vehicle_wire_color_full: 'yellow/white', color_source: 'as previously recorded in this model; no public source found to re-verify'}]->(b)
MATCH (a {id: 'positap_can_l'}), (b {id: 'porsche_987_2_can_drive'}) CREATE (a)-[:TAPS_VEHICLE_CAN {vehicle_id: 'porsche_987_2', bus_name: 'CAN Drive', signal: 'CAN-L', polarity: '-', vehicle_wire_color: 'BLK/WHT', vehicle_wire_color_full: 'black/white', color_source: 'as previously recorded in this model; no public source found to re-verify'}]->(b)
MATCH (a {id: 'esp_5v'}), (b {id: 'function:5V rail'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gnd_l'}), (b {id: 'function:Ground'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_3v3'}), (b {id: 'function:3.3V regulated output'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp0'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp0'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp0'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp0'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp0'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp0'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp2'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp2'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp2'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp2'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp2'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp2'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp2'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp3'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp3'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp3'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp3'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp3'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp3'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp3'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:UART1_RX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:UART1_RX'}) CREATE (a)-[:ASSIGNED_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:UART1_TX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:UART1_TX'}) CREATE (a)-[:ASSIGNED_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp6'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp6'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp6'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp6'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp6'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp6'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp6'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_txd0'}), (b {id: 'function:UART0_TX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_txd0'}), (b {id: 'function:USB/UART0 TX'}) CREATE (a)-[:ASSIGNED_FUNCTION {}]->(b)
MATCH (a {id: 'esp_rxd0'}), (b {id: 'function:UART0_RX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_rxd0'}), (b {id: 'function:USB/UART0 RX'}) CREATE (a)-[:ASSIGNED_FUNCTION {}]->(b)
MATCH (a {id: 'esp_vbat'}), (b {id: 'function:VBAT'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gnd_r'}), (b {id: 'function:Ground'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp11'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp11'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp11'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp11'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp11'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp11'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp11'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp10'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp10'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp10'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp10'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp10'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp10'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp10'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:TWAI_TX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:TWAI_TX'}) CREATE (a)-[:ASSIGNED_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:TWAI_RX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:TWAI_RX'}) CREATE (a)-[:ASSIGNED_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp7'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp7'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp7'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp7'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp7'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp7'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp7'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io12'}), (b {id: 'function:IMU_INT2'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io12'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io13'}), (b {id: 'function:IMU_INT1'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io14'}), (b {id: 'function:SD_SCLK'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io15'}), (b {id: 'function:SD_MOSI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io16'}), (b {id: 'function:SD_MISO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io17'}), (b {id: 'function:SD_D2'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io18'}), (b {id: 'function:SD_D1'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io19'}), (b {id: 'function:USB_N'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io20'}), (b {id: 'function:USB_P'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io21'}), (b {id: 'function:SD_CS'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io38'}), (b {id: 'function:RGB_IO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io39'}), (b {id: 'function:LCD_RST'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io40'}), (b {id: 'function:LCD_CLK'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io41'}), (b {id: 'function:LCD_DC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io42'}), (b {id: 'function:LCD_CS'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io43'}), (b {id: 'function:UART0_TX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io44'}), (b {id: 'function:UART0_RX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io45'}), (b {id: 'function:LCD_DIN'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io46'}), (b {id: 'function:LCD_BL'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io47'}), (b {id: 'function:IMU_SCL'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io48'}), (b {id: 'function:IMU_SDA'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp32_usb_vbus'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp32_usb_gnd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_usb_c'}), (b {id: 'esp32_usb_vbus'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_usb_c'}), (b {id: 'esp32_usb_gnd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_usb_vbus'}), (b {id: 'esp_5v'}) CREATE (a)-[:ELECTRICALLY_COMMON {net: '5V_USB', notes: 'USBC 5VBUS is the source of the board 5V rail.'}]->(b)
MATCH (a {id: 'esp32_usb_gnd'}), (b {id: 'esp_gnd_l'}) CREATE (a)-[:ELECTRICALLY_COMMON {net: 'GND', notes: 'USB-C ground is common with ESP32 external header ground.'}]->(b)
MATCH (a {id: 'esp32_usb_gnd'}), (b {id: 'esp_gnd_r'}) CREATE (a)-[:ELECTRICALLY_COMMON {net: 'GND', notes: 'USB-C ground is common with ESP32 external header ground.'}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp32_usb_dn'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp32_usb_dp'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_usb_c'}), (b {id: 'esp32_usb_dn'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_usb_c'}), (b {id: 'esp32_usb_dp'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_usb_dn'}), (b {id: 'esp_io19'}) CREATE (a)-[:ELECTRICALLY_COMMON {net: 'USB_D-', notes: 'On-board trace from the USB-C receptacle D- contacts to ESP32-S3 GPIO19.'}]->(b)
MATCH (a {id: 'esp32_usb_dp'}), (b {id: 'esp_io20'}) CREATE (a)-[:ELECTRICALLY_COMMON {net: 'USB_D+', notes: 'On-board trace from the USB-C receptacle D+ contacts to ESP32-S3 GPIO20.'}]->(b)
MATCH (a {id: 'host_usb_vbus'}), (b {id: 'esp32_usb_vbus'}) CREATE (a)-[:USB_CABLE {signal: '5V', conductor: 'VBUS', harness: 'usb_c_cable', direction: 'host to board', cable_location: 'external', detachable: true}]->(b)
MATCH (a {id: 'host_usb_gnd'}), (b {id: 'esp32_usb_gnd'}) CREATE (a)-[:USB_CABLE {signal: 'GND', conductor: 'GND', harness: 'usb_c_cable', cable_location: 'external', detachable: true}]->(b)
MATCH (a {id: 'host_usb_dp'}), (b {id: 'esp32_usb_dp'}) CREATE (a)-[:USB_CABLE {signal: 'USB_D+', conductor: 'D+', harness: 'usb_c_cable', protocol: 'USB 2.0 full speed, CDC-ACM serial and JTAG', cable_location: 'external', detachable: true}]->(b)
MATCH (a {id: 'host_usb_dn'}), (b {id: 'esp32_usb_dn'}) CREATE (a)-[:USB_CABLE {signal: 'USB_D-', conductor: 'D-', harness: 'usb_c_cable', protocol: 'USB 2.0 full speed, CDC-ACM serial and JTAG', cable_location: 'external', detachable: true}]->(b)
MATCH (a {id: 'fan'}), (b {id: 'fan_vplus'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'fan'}), (b {id: 'fan_gnd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'can_logic_power_plug'}), (b {id: 'can_plug_vcc'}) CREATE (a)-[:HAS_PIN {position: 1}]->(b)
MATCH (a {id: 'can_logic_power_plug'}), (b {id: 'can_plug_gnd'}) CREATE (a)-[:HAS_PIN {position: 2}]->(b)
MATCH (a {id: 'can_logic_power_plug'}), (b {id: 'can_plug_rxd'}) CREATE (a)-[:HAS_PIN {position: 3}]->(b)
MATCH (a {id: 'can_logic_power_plug'}), (b {id: 'can_plug_txd'}) CREATE (a)-[:HAS_PIN {position: 4}]->(b)
MATCH (a {id: 'can_logic_power_plug'}), (b {id: 'sn65_logic_power_connector'}) CREATE (a)-[:MATES_WITH {positions: 4, detachable: true}]->(b)
MATCH (a {id: 'can_plug_vcc'}), (b {id: 'can_vcc'}) CREATE (a)-[:MATES_WITH {position: 1, signal: '3.3V'}]->(b)
MATCH (a {id: 'can_plug_gnd'}), (b {id: 'can_gnd'}) CREATE (a)-[:MATES_WITH {position: 2, signal: 'GND'}]->(b)
MATCH (a {id: 'can_plug_rxd'}), (b {id: 'can_rxd'}) CREATE (a)-[:MATES_WITH {position: 3, signal: 'SN65_RXD_TO_ESP32_TWAI_RX'}]->(b)
MATCH (a {id: 'can_plug_txd'}), (b {id: 'can_txd'}) CREATE (a)-[:MATES_WITH {position: 4, signal: 'ESP32_TWAI_TX_TO_SN65_TXD'}]->(b)
MATCH (a {id: 'esp32_power_plug'}), (b {id: 'esp_plug_5v'}) CREATE (a)-[:HAS_PIN {position: 1}]->(b)
MATCH (a {id: 'esp32_power_plug'}), (b {id: 'esp_plug_gnd'}) CREATE (a)-[:HAS_PIN {position: 2}]->(b)
MATCH (a {id: 'esp32_power_plug'}), (b {id: 'esp_plug_3v3'}) CREATE (a)-[:HAS_PIN {position: 3}]->(b)
MATCH (a {id: 'esp_plug_5v'}), (b {id: 'esp_5v'}) CREATE (a)-[:MATES_WITH {position: 1, header_order: 1, signal: '5V'}]->(b)
MATCH (a {id: 'esp_plug_gnd'}), (b {id: 'esp_gnd_l'}) CREATE (a)-[:MATES_WITH {position: 2, header_order: 2, signal: 'GND'}]->(b)
MATCH (a {id: 'esp_plug_3v3'}), (b {id: 'esp_3v3'}) CREATE (a)-[:MATES_WITH {position: 3, header_order: 3, signal: '3.3V'}]->(b)
MATCH (a {id: 'lg290p_uart_connector'}), (b {id: 'gps_vcc'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p_uart_connector'}), (b {id: 'gps_gnd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p_uart_connector'}), (b {id: 'gps_tx'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p_uart_connector'}), (b {id: 'gps_rx'}) CREATE (a)-[:HAS_PIN {}]->(b)

// Every contact belongs to a connector: board headers, harness housings and cable ends.
// Header positions are carried by header_side and header_order on each pin.
MATCH (a {id: 'esp32'}), (b {id: 'esp32_header_left'}) CREATE (a)-[:HAS_CONNECTOR {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp32_header_right'}) CREATE (a)-[:HAS_CONNECTOR {}]->(b)
MATCH (a {id: 'esp32_header_left'}), (b {id: 'esp_5v'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_left'}), (b {id: 'esp_gnd_l'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_left'}), (b {id: 'esp_3v3'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_left'}), (b {id: 'esp_gp0'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_left'}), (b {id: 'esp_gp2'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_left'}), (b {id: 'esp_gp3'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_left'}), (b {id: 'esp_gp4'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_left'}), (b {id: 'esp_gp5'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_left'}), (b {id: 'esp_gp6'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_right'}), (b {id: 'esp_txd0'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_right'}), (b {id: 'esp_rxd0'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_right'}), (b {id: 'esp_vbat'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_right'}), (b {id: 'esp_gnd_r'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_right'}), (b {id: 'esp_gp11'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_right'}), (b {id: 'esp_gp10'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_right'}), (b {id: 'esp_gp9'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_right'}), (b {id: 'esp_gp8'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_header_right'}), (b {id: 'esp_gp7'}) CREATE (a)-[:HAS_PIN {}]->(b)

MATCH (a {id: 'esp32_gps_uart_plug'}), (b {id: 'esp_uplug_rx'}) CREATE (a)-[:HAS_PIN {position: 1}]->(b)
MATCH (a {id: 'esp32_gps_uart_plug'}), (b {id: 'esp_uplug_tx'}) CREATE (a)-[:HAS_PIN {position: 2}]->(b)
MATCH (a {id: 'esp32_gps_uart_plug'}), (b {id: 'esp32_header_left'}) CREATE (a)-[:MATES_WITH {positions: 2, header_positions: '7-8', detachable: true}]->(b)
MATCH (a {id: 'esp_uplug_rx'}), (b {id: 'esp_gp4'}) CREATE (a)-[:MATES_WITH {position: 1, header_order: 7, signal: 'LG290P_TX_TO_ESP32_UART1_RX'}]->(b)
MATCH (a {id: 'esp_uplug_tx'}), (b {id: 'esp_gp5'}) CREATE (a)-[:MATES_WITH {position: 2, header_order: 8, signal: 'ESP32_UART1_TX_TO_LG290P_RX'}]->(b)

MATCH (a {id: 'esp32_can_logic_plug'}), (b {id: 'esp_cplug_tx'}) CREATE (a)-[:HAS_PIN {position: 1}]->(b)
MATCH (a {id: 'esp32_can_logic_plug'}), (b {id: 'esp_cplug_rx'}) CREATE (a)-[:HAS_PIN {position: 2}]->(b)
MATCH (a {id: 'esp32_can_logic_plug'}), (b {id: 'esp32_header_right'}) CREATE (a)-[:MATES_WITH {positions: 2, header_positions: '7-8', detachable: true}]->(b)
MATCH (a {id: 'esp_cplug_tx'}), (b {id: 'esp_gp9'}) CREATE (a)-[:MATES_WITH {position: 1, header_order: 7, signal: 'ESP32_TWAI_TX_TO_SN65_TXD'}]->(b)
MATCH (a {id: 'esp_cplug_rx'}), (b {id: 'esp_gp8'}) CREATE (a)-[:MATES_WITH {position: 2, header_order: 8, signal: 'SN65_RXD_TO_ESP32_TWAI_RX'}]->(b)

MATCH (a {id: 'lg290p_uart_cable_plug'}), (b {id: 'gps_plug_vcc'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p_uart_cable_plug'}), (b {id: 'gps_plug_gnd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p_uart_cable_plug'}), (b {id: 'gps_plug_tx'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p_uart_cable_plug'}), (b {id: 'gps_plug_rx'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p_uart_cable_plug'}), (b {id: 'lg290p_uart_connector'}) CREATE (a)-[:MATES_WITH {series: 'JST SH', positions: 4, detachable: true}]->(b)
MATCH (a {id: 'gps_plug_vcc'}), (b {id: 'gps_vcc'}) CREATE (a)-[:MATES_WITH {signal: '3.3V'}]->(b)
MATCH (a {id: 'gps_plug_gnd'}), (b {id: 'gps_gnd'}) CREATE (a)-[:MATES_WITH {signal: 'GND'}]->(b)
MATCH (a {id: 'gps_plug_tx'}), (b {id: 'gps_tx'}) CREATE (a)-[:MATES_WITH {signal: 'LG290P_TX_TO_ESP32_UART1_RX'}]->(b)
MATCH (a {id: 'gps_plug_rx'}), (b {id: 'gps_rx'}) CREATE (a)-[:MATES_WITH {signal: 'ESP32_UART1_TX_TO_LG290P_RX'}]->(b)

MATCH (a {id: 'lg290p'}), (b {id: 'gps_rf_in'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p_antenna_connector'}), (b {id: 'gps_rf_in'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'external_gnss_antenna'}), (b {id: 'antenna_rf_out'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'antenna_cable_plug'}), (b {id: 'antenna_plug_rf'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'antenna_cable_plug'}), (b {id: 'lg290p_antenna_connector'}) CREATE (a)-[:MATES_WITH {detachable: true}]->(b)
MATCH (a {id: 'antenna_plug_rf'}), (b {id: 'gps_rf_in'}) CREATE (a)-[:MATES_WITH {signal: 'GNSS RF'}]->(b)

MATCH (a {id: 'host_pc'}), (b {id: 'host_usb_port'}) CREATE (a)-[:HAS_CONNECTOR {}]->(b)
MATCH (a {id: 'host_usb_port'}), (b {id: 'host_usb_vbus'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'host_usb_port'}), (b {id: 'host_usb_gnd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'host_usb_port'}), (b {id: 'host_usb_dp'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'host_usb_port'}), (b {id: 'host_usb_dn'}) CREATE (a)-[:HAS_PIN {}]->(b)

MATCH (a {id: 'rcx_enclosure'}), (b {id: 'esp32_gps_uart_plug'}) CREATE (a)-[:CONTAINS {}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'esp32_can_logic_plug'}) CREATE (a)-[:CONTAINS {}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'lg290p_uart_cable_plug'}) CREATE (a)-[:CONTAINS {}]->(b)

// Configuration alternatives.
MATCH (a {id: 'vp_usb_c'}), (b {id: 'var_usb_power'}) CREATE (a)-[:HAS_VARIANT {}]->(b)
MATCH (a {id: 'vp_usb_c'}), (b {id: 'var_usb_pc'}) CREATE (a)-[:HAS_VARIANT {}]->(b)
MATCH (a {id: 'vp_vehicle_bus'}), (b {id: 'var_718_chassis'}) CREATE (a)-[:HAS_VARIANT {}]->(b)
MATCH (a {id: 'vp_vehicle_bus'}), (b {id: 'var_718_drive'}) CREATE (a)-[:HAS_VARIANT {}]->(b)
MATCH (a {id: 'vp_vehicle_bus'}), (b {id: 'var_987_2_drive'}) CREATE (a)-[:HAS_VARIANT {}]->(b)
MATCH (a {id: 'vp_vehicle_bus'}), (b {id: 'var_frs_obd'}) CREATE (a)-[:HAS_VARIANT {}]->(b)
MATCH (a {id: 'vp_vehicle_bus'}), (b {id: 'var_no_vehicle'}) CREATE (a)-[:HAS_VARIANT {}]->(b)

// In use: the USB-C cable runs from a USB power source.
MATCH (a {id: 'usb_power_source'}), (b {id: 'usb_power_port'}) CREATE (a)-[:HAS_CONNECTOR {}]->(b)
MATCH (a {id: 'usb_power_port'}), (b {id: 'usb_power_vbus'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'usb_power_port'}), (b {id: 'usb_power_gnd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'usb_power_port'}), (b {id: 'usb_power_dp'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'usb_power_port'}), (b {id: 'usb_power_dn'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'usb_power_vbus'}), (b {id: 'esp32_usb_vbus'}) CREATE (a)-[:USB_CABLE {signal: '5V', conductor: 'VBUS', harness: 'usb_c_cable', direction: 'supply to board', cable_location: 'external', detachable: true}]->(b)
MATCH (a {id: 'usb_power_gnd'}), (b {id: 'esp32_usb_gnd'}) CREATE (a)-[:USB_CABLE {signal: 'GND', conductor: 'GND', harness: 'usb_c_cable', cable_location: 'external', detachable: true}]->(b)
MATCH (a {id: 'usb_power_dp'}), (b {id: 'esp32_usb_dp'}) CREATE (a)-[:USB_CABLE {signal: 'USB_D+', conductor: 'D+', harness: 'usb_c_cable', cable_location: 'external', detachable: true, notes: 'Conductor present in the cable; no data with a power source.'}]->(b)
MATCH (a {id: 'usb_power_dn'}), (b {id: 'esp32_usb_dn'}) CREATE (a)-[:USB_CABLE {signal: 'USB_D-', conductor: 'D-', harness: 'usb_c_cable', cable_location: 'external', detachable: true, notes: 'Conductor present in the cable; no data with a power source.'}]->(b)

// Porsche 718 chassis bus through the same PosiTaps.
MATCH (a {id: 'porsche_718'}), (b {id: 'porsche_718_can_chassis'}) CREATE (a)-[:HAS_CAN_BUS {}]->(b)
MATCH (a {id: 'positap_can_h'}), (b {id: 'porsche_718_can_chassis'}) CREATE (a)-[:TAPS_VEHICLE_CAN {vehicle_id: 'porsche_718', bus_name: 'Chassis CAN', signal: 'CAN-H', polarity: '+', vehicle_wire_color: 'ORG/VIO', vehicle_wire_color_full: 'orange/violet', color_status: 'unconfirmed: owner recollection; no readable source found', color_source: 'Owner recollection (orange/purple). Consistent with the VAG pattern (orange base, bus-specific stripe on CAN-High), but VW service information assigns orange/violet to the infotainment CAN; the Rennlist thread "718 CAN Chassis Bus Decoding" could not be opened to confirm.'}]->(b)
MATCH (a {id: 'positap_can_l'}), (b {id: 'porsche_718_can_chassis'}) CREATE (a)-[:TAPS_VEHICLE_CAN {vehicle_id: 'porsche_718', bus_name: 'Chassis CAN', signal: 'CAN-L', polarity: '-', vehicle_wire_color: 'ORG/BRN', vehicle_wire_color_full: 'orange/brown', color_status: 'unconfirmed for this bus; matches the VAG convention', color_source: 'Owner recollection; VW service information gives orange/brown for every CAN-Low. No 718 chassis-specific source could be opened.'}]->(b)

// Scion FR-S: the OBD-II lead plugs into the car's diagnostic port.
MATCH (a {id: 'scion_frs'}), (b {id: 'scion_frs_can'}) CREATE (a)-[:HAS_CAN_BUS {}]->(b)
MATCH (a {id: 'scion_frs_can'}), (b {id: 'frs_obd_port'}) CREATE (a)-[:HAS_CONNECTOR {}]->(b)
MATCH (a {id: 'frs_obd_port'}), (b {id: 'frs_obd_6'}) CREATE (a)-[:HAS_PIN {position: 6}]->(b)
MATCH (a {id: 'frs_obd_port'}), (b {id: 'frs_obd_14'}) CREATE (a)-[:HAS_PIN {position: 14}]->(b)
MATCH (a {id: 'obd_lead_socket'}), (b {id: 'obd_lead_pin1'}) CREATE (a)-[:HAS_PIN {position: 1}]->(b)
MATCH (a {id: 'obd_lead_socket'}), (b {id: 'obd_lead_pin2'}) CREATE (a)-[:HAS_PIN {position: 2}]->(b)
MATCH (a {id: 'obd_lead_plug'}), (b {id: 'obd_plug_6'}) CREATE (a)-[:HAS_PIN {position: 6}]->(b)
MATCH (a {id: 'obd_lead_plug'}), (b {id: 'obd_plug_14'}) CREATE (a)-[:HAS_PIN {position: 14}]->(b)
MATCH (a {id: 'obd_lead_socket'}), (b {id: 'can_pigtail_plug'}) CREATE (a)-[:MATES_WITH {series: 'Dupont', positions: 2, detachable: true}]->(b)
MATCH (a {id: 'obd_lead_pin1'}), (b {id: 'can_pigtail_plug_pin1'}) CREATE (a)-[:MATES_WITH {position: 1, signal: 'CAN-L'}]->(b)
MATCH (a {id: 'obd_lead_pin2'}), (b {id: 'can_pigtail_plug_pin2'}) CREATE (a)-[:MATES_WITH {position: 2, signal: 'CAN-H'}]->(b)
MATCH (a {id: 'obd_lead_pin1'}), (b {id: 'obd_plug_14'}) CREATE (a)-[:WIRE {id: 'w_obd_lead_canl', signal: 'CAN-L', polarity: '-', harness: 'obd_can_lead', notes: 'Removable OBD-II lead: Dupont pin 1 to OBD-II pin 14.'}]->(b)
MATCH (a {id: 'obd_lead_pin2'}), (b {id: 'obd_plug_6'}) CREATE (a)-[:WIRE {id: 'w_obd_lead_canh', signal: 'CAN-H', polarity: '+', harness: 'obd_can_lead', notes: 'Removable OBD-II lead: Dupont pin 2 to OBD-II pin 6.'}]->(b)
MATCH (a {id: 'obd_lead_plug'}), (b {id: 'frs_obd_port'}) CREATE (a)-[:MATES_WITH {standard: 'SAE J1962', detachable: true}]->(b)
MATCH (a {id: 'obd_plug_6'}), (b {id: 'frs_obd_6'}) CREATE (a)-[:MATES_WITH {position: 6, signal: 'CAN-H'}]->(b)
MATCH (a {id: 'obd_plug_14'}), (b {id: 'frs_obd_14'}) CREATE (a)-[:MATES_WITH {position: 14, signal: 'CAN-L'}]->(b)
