// RCX RTK Datalogger — wiring knowledge graph logical physics model

CREATE (esp32:Device {id: 'esp32', name: 'ESP32-S3-LCD-1.47B', type: 'MCU board', manufacturer: 'Waveshare', input_power: '5V via onboard USB-C connector', logic_level: '3.3V', physical_position_status: 'partial: external-header side and order are captured; millimeter pin coordinates are not yet captured', notes: 'ESP32-S3 board with onboard LCD, SD card, IMU, USB-C power/data, and external GPIO header.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'primary', diagram_group: 'controller', diagram_order: 10})
CREATE (lg290p:Device {id: 'lg290p', name: 'LG290P RTK GNSS module', type: 'GNSS receiver', voltage_in: '3.3V', logic_level: '3.3V', physical_position_status: 'connector ownership is captured; pin order and millimeter coordinates are not yet captured', notes: 'GNSS module powered from ESP32 3V3 rail through the 2-pin power splitter. UART connector is physically on the GPS module.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'primary', diagram_group: 'gnss', diagram_order: 30})
CREATE (sn65:Device {id: 'sn65', name: 'SN65HVD230 CAN transceiver module', type: 'CAN transceiver breakout', voltage_in: '3.3V', logic_level: '3.3V', can_physical_layer: 'ISO 11898-2 high-speed CAN', physical_position_status: 'dimensioned from user-supplied STEP/STL', coordinate_frame: 'sn65_component_side_xz_v1', cad_source_step: 'CAN Transiver SN65HVD230.step', cad_source_stl: 'CAN Transiver SN65HVD230.stl', assembly_size_x_mm: 32.4903, assembly_size_y_mm: 10.2756, assembly_height_mm: 13.7764, notes: '3.3V CAN transceiver used as receive interface for vehicle CAN. TXD is wired but firmware may operate in listen-only mode.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'primary', diagram_group: 'can', diagram_order: 40})
CREATE (esp32_usb_c:Connector {id: 'esp32_usb_c', name: 'ESP32 onboard USB-C connector', device: 'esp32', type: 'USB-C receptacle', role: '5V power input and USB serial', physical_location: 'top edge of ESP32 board', notes: 'External 5V USB-C power is applied here. No separate external power-supply node is part of the internal harness model.', physical_model: 'Connector is physically mounted on and logically owned by the ESP32-S3 board.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', interface_exposure: 'external', external_interface: true, interface_type: 'power_usb', cover_label: 'USB-C / 5V INPUT', cover_order: 10, diagram_level: 'primary', diagram_group: 'external_interface', diagram_order: 15})
CREATE (pwr_splitter:Connector {id: 'pwr_splitter', name: '2-pin 3.3V/GND power splitter cable', type: 'Y splitter harness', role: 'Distributes ESP32 3.3V and GND to GPS and CAN modules', notes: 'Input side connects to ESP32 3V3(OUT) and GND pins. Output side provides two 2-pin male connectors.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'primary', diagram_group: 'power', diagram_order: 20})
CREATE (pwr_splitter_input:Connector {id: 'pwr_splitter_input', name: 'Power splitter input plug', type: '2-pin connector', gender: 'female or board-side lead', parent: 'pwr_splitter', notes: 'Connects to ESP32 external header 3V3(OUT) and GND.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'detail'})
CREATE (pwr_splitter_gps_out:Connector {id: 'pwr_splitter_gps_out', name: 'GPS power output', type: '2-pin male connector', parent: 'pwr_splitter', notes: 'Feeds LG290P 3.3V and GND.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'detail'})
CREATE (pwr_splitter_can_out:Connector {id: 'pwr_splitter_can_out', name: 'CAN module power output', type: '2-pin male connector', parent: 'pwr_splitter', notes: 'Feeds SN65HVD230 VCC and GND.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'detail'})
CREATE (lg290p_uart_connector:Connector {id: 'lg290p_uart_connector', name: 'LG290P onboard UART connector', type: '4-pin module connector', device: 'lg290p', pins: '3.3V, GND, TX, RX', notes: 'This connector is physically on the GPS module, not a separate inline harness connector.', physical_model: 'Connector is physically mounted on and logically owned by the LG290P module.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'detail'})
CREATE (sn65_logic_power_connector:Connector {id: 'sn65_logic_power_connector', name: 'SN65HVD230 4-pin logic/power header', type: '1x4 male pin header', device: 'sn65', positions: 4, nominal_pitch_mm: 2.54, measured_pitch_mm: 2.52, pins_component_side_top_to_bottom: ['VCC', 'GND', 'RXD', 'TXD'], physical_edge: 'logic-header end', contact_direction: '-X in sn65_component_side_xz_v1', notes: 'Carries 3.3V, ground, TWAI RXD, and TWAI TXD between the ESP32/power splitter and the CAN transceiver module.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'detail'})
CREATE (sn65_can_screw_terminal:Connector {id: 'sn65_can_screw_terminal', name: 'SN65HVD230 CAN screw terminal', type: '2-position PCB screw terminal', device: 'sn65', positions: 2, preferred_connection: true, position_1_signal: 'CANL', position_2_signal: 'CANH', component_side_order: 'CANL upper, CANH lower', measured_center_spacing_mm: 4.7390, notes: 'CANH and CANL screw terminals are electrically parallel with the nearby plated pads. Normal installation uses the screw terminals.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'detail'})
CREATE (sn65_can_parallel_pads:Connector {id: 'sn65_can_parallel_pads', name: 'SN65HVD230 parallel CAN pads', type: '2-position plated through-hole pads', device: 'sn65', positions: 2, preferred_connection: false, position_1_signal: 'CANL', position_2_signal: 'CANH', component_side_order: 'CANL upper, CANH lower', measured_center_spacing_mm: 2.52, notes: 'These pads are electrically parallel with the CAN screw terminals and are normally unused.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'detail'})
CREATE (backplane_can_jst_xh_female:Connector {id: 'backplane_can_jst_xh_female', name: 'Backplane CAN JST-XH female housing', type: 'JST-XH 2-position housing', series: 'JST XH', positions: 2, nominal_pitch_mm: 2.5, user_gender: 'female housing', mounting: 'fixed to backplane', location: 'internal', pin_1_signal: 'CANL', pin_2_signal: 'CANH', physical_position_status: 'backplane mounting coordinates TBD', notes: 'User-defined connector terminology: female housing is internal/fixed. Pin 1 is CANL; pin 2 is CANH.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', interface_exposure: 'external', external_interface: true, interface_type: 'vehicle_can', cover_label: 'VEHICLE CAN', cover_order: 30, diagram_level: 'primary', diagram_group: 'external_interface', diagram_order: 50})
CREATE (can_wire_jst_xh_male:Connector {id: 'can_wire_jst_xh_male', name: 'Removable CAN-wire JST-XH male plug', type: 'JST-XH 2-position plug', series: 'JST XH', positions: 2, nominal_pitch_mm: 2.5, user_gender: 'male plug', mounting: 'on removable CAN wire', location: 'removable harness', pin_1_signal: 'CANL', pin_2_signal: 'CANH', notes: 'User-defined connector terminology: male plug is on the removable CAN lead. Pin 1 is CANL; pin 2 is CANH.', enclosure_scope: 'external', external_removable: true, diagram_level: 'primary', diagram_group: 'external_harness', diagram_order: 60})
CREATE (sn65_frame:CoordinateFrame {id: 'sn65_component_side_xz_v1', device: 'sn65', name: 'SN65 component-side board coordinate frame', units: 'mm', source: 'user-supplied STEP/STL', drawing_plane: 'STL X-Z projection', origin: 'STL minimum X and minimum Z', x_axis: 'logic header toward screw terminal', y_axis: 'lower CANH side toward upper CANL side; equals STL +Z', height_axis: 'STL +Y away from PCB base', position_accuracy_mm: 0.05})
CREATE (positap_can_h:Connector {id: 'positap_can_h', name: 'PosiTap CAN-H', type: 'direct tap connector', role: 'tap onto vehicle CAN-H', signal: 'CAN-H', polarity: '+', tap_lead_color: 'white', mapping_scope: 'Vehicle-specific bus and wire color are defined on TAPS_VEHICLE_CAN relationships.', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'vehicle_tap', diagram_order: 70})
CREATE (positap_can_l:Connector {id: 'positap_can_l', name: 'PosiTap CAN-L', type: 'direct tap connector', role: 'tap onto vehicle CAN-L', signal: 'CAN-L', polarity: '-', tap_lead_color: 'green', mapping_scope: 'Vehicle-specific bus and wire color are defined on TAPS_VEHICLE_CAN relationships.', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'vehicle_tap', diagram_order: 71})


// Enclosure-boundary and external-interface model.
CREATE (rcx_enclosure:Enclosure {id: 'rcx_enclosure', name: 'RCX RTK Datalogger enclosure', type: '3D-printed electronics enclosure', diagram_level: 'primary', diagram_group: 'enclosure', diagram_order: 0, notes: 'Internal electronics are contained here. Externally accessible interfaces are USB-C power, the GNSS antenna connection, and the removable vehicle-CAN JST-XH connection.'})
CREATE (lg290p_antenna_connector:Connector {id: 'lg290p_antenna_connector', name: 'LG290P antenna connector', device: 'lg290p', type: 'RF antenna connector', connector_standard: 'TBD from exact LG290P carrier/module', role: 'GNSS RF input', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', interface_exposure: 'external', external_interface: true, interface_type: 'gnss_antenna', cover_label: 'GNSS ANTENNA', cover_order: 20, diagram_level: 'primary', diagram_group: 'external_interface', diagram_order: 35, physical_position_status: 'connector location and standard not yet dimensioned', notes: 'Externally accessible antenna connection on the LG290P module.'})
CREATE (external_gnss_antenna:Antenna {id: 'external_gnss_antenna', name: 'External multiband GNSS antenna', type: 'active GNSS antenna', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'external_device', diagram_order: 65, mounting: 'vehicle exterior or other sky-view location', notes: 'External antenna connects to the LG290P antenna connector through its RF cable.'})
// Vehicle-specific CAN mappings. Vehicle wire colors belong to the tap-to-bus
// relationship, not globally to either the PosiTap or CAN bus node.
CREATE (porsche_718:Vehicle {id: 'porsche_718', manufacturer: 'Porsche', model: '718', generation: '982', name: 'Porsche 718', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'vehicle', diagram_order: 90})
CREATE (porsche_987_2:Vehicle {id: 'porsche_987_2', manufacturer: 'Porsche', model: '987.2', generation: '987.2', name: 'Porsche 987.2', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'vehicle', diagram_order: 91})
CREATE (porsche_718_can_drive_high:CANBus {id: 'porsche_718_can_drive_high', name: 'CAN Drive High', vehicle_id: 'porsche_718', network_role: 'drive/powertrain CAN', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'vehicle_bus', diagram_order: 80})
CREATE (porsche_987_2_can_drive:CANBus {id: 'porsche_987_2_can_drive', name: 'CAN Drive', vehicle_id: 'porsche_987_2', network_role: 'drive/powertrain CAN', enclosure_scope: 'external', diagram_level: 'primary', diagram_group: 'vehicle_bus', diagram_order: 81})
CREATE (esp_5v:Pin {id: 'esp_5v', device: 'esp32', connector: 'external_header', name: '5V', type: 'power', direction: 'IN/OUT', voltage: '5V', header_side: 'left', header_order: 1, functions: ['5V rail']})
CREATE (esp_gnd_l:Pin {id: 'esp_gnd_l', device: 'esp32', connector: 'external_header', name: 'GND', type: 'ground', header_side: 'left', header_order: 2, functions: ['Ground']})
CREATE (esp_3v3:Pin {id: 'esp_3v3', device: 'esp32', connector: 'external_header', name: '3V3(OUT)', type: 'power_out', direction: 'OUT', voltage: '3.3V', header_side: 'left', header_order: 3, functions: ['3.3V regulated output']})
CREATE (esp_gp0:Pin {id: 'esp_gp0', device: 'esp32', connector: 'external_header', name: 'GP0', type: 'gpio', logic: '3.3V', header_side: 'left', header_order: 4, functions: ['UART', 'PWM', 'I2S', 'I2C', 'SPI', 'GPIO']})
CREATE (esp_gp2:Pin {id: 'esp_gp2', device: 'esp32', connector: 'external_header', name: 'GP2', type: 'gpio', logic: '3.3V', header_side: 'left', header_order: 5, functions: ['UART', 'PWM', 'I2S', 'ADC', 'I2C', 'SPI', 'GPIO']})
CREATE (esp_gp3:Pin {id: 'esp_gp3', device: 'esp32', connector: 'external_header', name: 'GP3', type: 'gpio', logic: '3.3V', header_side: 'left', header_order: 6, functions: ['UART', 'PWM', 'I2S', 'ADC', 'I2C', 'SPI', 'GPIO']})
CREATE (esp_gp4:Pin {id: 'esp_gp4', device: 'esp32', connector: 'external_header', name: 'GP4', type: 'gpio', logic: '3.3V', header_side: 'left', header_order: 7, functions: ['UART', 'PWM', 'I2S', 'ADC', 'I2C', 'SPI', 'GPIO', 'UART1_RX'], assigned_function: 'UART1_RX', direction: 'IN', notes: 'Receives LG290P TX'})
CREATE (esp_gp5:Pin {id: 'esp_gp5', device: 'esp32', connector: 'external_header', name: 'GP5', type: 'gpio', logic: '3.3V', header_side: 'left', header_order: 8, functions: ['UART', 'PWM', 'I2S', 'ADC', 'I2C', 'SPI', 'GPIO', 'UART1_TX'], assigned_function: 'UART1_TX', direction: 'OUT', notes: 'Transmits to LG290P RX'})
CREATE (esp_gp6:Pin {id: 'esp_gp6', device: 'esp32', connector: 'external_header', name: 'GP6', type: 'gpio', logic: '3.3V', header_side: 'left', header_order: 9, functions: ['UART', 'PWM', 'I2S', 'ADC', 'I2C', 'SPI', 'GPIO']})
CREATE (esp_txd0:Pin {id: 'esp_txd0', device: 'esp32', connector: 'external_header', name: 'TX', type: 'gpio', logic: '3.3V', header_side: 'right', header_order: 1, functions: ['UART0_TX'], assigned_function: 'USB/UART0 TX'})
CREATE (esp_rxd0:Pin {id: 'esp_rxd0', device: 'esp32', connector: 'external_header', name: 'RX', type: 'gpio', logic: '3.3V', header_side: 'right', header_order: 2, functions: ['UART0_RX'], assigned_function: 'USB/UART0 RX'})
CREATE (esp_vbat:Pin {id: 'esp_vbat', device: 'esp32', connector: 'external_header', name: 'VBAT', type: 'power', header_side: 'right', header_order: 3, functions: ['VBAT']})
CREATE (esp_gnd_r:Pin {id: 'esp_gnd_r', device: 'esp32', connector: 'external_header', name: 'GND', type: 'ground', header_side: 'right', header_order: 4, functions: ['Ground']})
CREATE (esp_gp11:Pin {id: 'esp_gp11', device: 'esp32', connector: 'external_header', name: 'GP11', type: 'gpio', logic: '3.3V', header_side: 'right', header_order: 5, functions: ['SPI', 'I2C', 'ADC', 'I2S', 'PWM', 'UART', 'GPIO']})
CREATE (esp_gp10:Pin {id: 'esp_gp10', device: 'esp32', connector: 'external_header', name: 'GP10', type: 'gpio', logic: '3.3V', header_side: 'right', header_order: 6, functions: ['SPI', 'I2C', 'ADC', 'I2S', 'PWM', 'UART', 'GPIO']})
CREATE (esp_gp9:Pin {id: 'esp_gp9', device: 'esp32', connector: 'external_header', name: 'GP9', type: 'gpio', logic: '3.3V', header_side: 'right', header_order: 7, functions: ['SPI', 'I2C', 'ADC', 'I2S', 'PWM', 'UART', 'GPIO', 'TWAI_TX'], assigned_function: 'TWAI_TX', direction: 'OUT', notes: 'Correct mapping: TWAI TX is GPIO9. Wired to SN65 TXD; typically listen-only.'})
CREATE (esp_gp8:Pin {id: 'esp_gp8', device: 'esp32', connector: 'external_header', name: 'GP8', type: 'gpio', logic: '3.3V', header_side: 'right', header_order: 8, functions: ['SPI', 'I2C', 'ADC', 'I2S', 'PWM', 'UART', 'GPIO', 'TWAI_RX'], assigned_function: 'TWAI_RX', direction: 'IN', notes: 'Correct mapping: TWAI RX is GPIO8. Receives SN65 RXD.'})
CREATE (esp_gp7:Pin {id: 'esp_gp7', device: 'esp32', connector: 'external_header', name: 'GP7', type: 'gpio', logic: '3.3V', header_side: 'right', header_order: 9, functions: ['SPI', 'I2C', 'ADC', 'I2S', 'PWM', 'UART', 'GPIO']})
CREATE (esp_io12:Pin {id: 'esp_io12', device: 'esp32', name: 'IO12', type: 'internal_gpio', functions: ['IMU_INT2', 'GPIO']})
CREATE (esp_io13:Pin {id: 'esp_io13', device: 'esp32', name: 'IO13', type: 'internal_gpio', functions: ['IMU_INT1']})
CREATE (esp_io14:Pin {id: 'esp_io14', device: 'esp32', name: 'IO14', type: 'internal_gpio', functions: ['SD_SCLK']})
CREATE (esp_io15:Pin {id: 'esp_io15', device: 'esp32', name: 'IO15', type: 'internal_gpio', functions: ['SD_MOSI']})
CREATE (esp_io16:Pin {id: 'esp_io16', device: 'esp32', name: 'IO16', type: 'internal_gpio', functions: ['SD_MISO']})
CREATE (esp_io17:Pin {id: 'esp_io17', device: 'esp32', name: 'IO17', type: 'internal_gpio', functions: ['SD_D2']})
CREATE (esp_io18:Pin {id: 'esp_io18', device: 'esp32', name: 'IO18', type: 'internal_gpio', functions: ['SD_D1']})
CREATE (esp_io19:Pin {id: 'esp_io19', device: 'esp32', name: 'IO19', type: 'internal_gpio', functions: []})
CREATE (esp_io20:Pin {id: 'esp_io20', device: 'esp32', name: 'IO20', type: 'internal_gpio', functions: []})
CREATE (esp_io21:Pin {id: 'esp_io21', device: 'esp32', name: 'IO21', type: 'internal_gpio', functions: ['SD_CS']})
CREATE (esp_io38:Pin {id: 'esp_io38', device: 'esp32', name: 'IO38', type: 'internal_gpio', functions: ['RGB_IO']})
CREATE (esp_io39:Pin {id: 'esp_io39', device: 'esp32', name: 'IO39', type: 'internal_gpio', functions: ['LCD_RST']})
CREATE (esp_io40:Pin {id: 'esp_io40', device: 'esp32', name: 'IO40', type: 'internal_gpio', functions: ['LCD_CLK']})
CREATE (esp_io41:Pin {id: 'esp_io41', device: 'esp32', name: 'IO41', type: 'internal_gpio', functions: ['LCD_DC']})
CREATE (esp_io42:Pin {id: 'esp_io42', device: 'esp32', name: 'IO42', type: 'internal_gpio', functions: ['LCD_CS']})
CREATE (esp_io43:Pin {id: 'esp_io43', device: 'esp32', name: 'IO43', type: 'internal_gpio', functions: ['UART0_TX']})
CREATE (esp_io44:Pin {id: 'esp_io44', device: 'esp32', name: 'IO44', type: 'internal_gpio', functions: ['UART0_RX']})
CREATE (esp_io45:Pin {id: 'esp_io45', device: 'esp32', name: 'IO45', type: 'internal_gpio', functions: ['LCD_DIN']})
CREATE (esp_io46:Pin {id: 'esp_io46', device: 'esp32', name: 'IO46', type: 'internal_gpio', functions: ['LCD_BL']})
CREATE (esp_io47:Pin {id: 'esp_io47', device: 'esp32', name: 'IO47', type: 'internal_gpio', functions: ['IMU_SCL']})
CREATE (esp_io48:Pin {id: 'esp_io48', device: 'esp32', name: 'IO48', type: 'internal_gpio', functions: ['IMU_SDA']})
CREATE (gps_vcc:Pin {id: 'gps_vcc', device: 'lg290p', connector: 'lg290p_uart_connector', name: '3.3V', type: 'power_in', voltage: '3.3V'})
CREATE (gps_gnd:Pin {id: 'gps_gnd', device: 'lg290p', connector: 'lg290p_uart_connector', name: 'GND', type: 'ground'})
CREATE (gps_tx:Pin {id: 'gps_tx', device: 'lg290p', connector: 'lg290p_uart_connector', name: 'TX', type: 'signal', direction: 'OUT', logic: '3.3V', notes: 'GNSS TX to ESP32 UART1_RX / GP4'})
CREATE (gps_rx:Pin {id: 'gps_rx', device: 'lg290p', connector: 'lg290p_uart_connector', name: 'RX', type: 'signal', direction: 'IN', logic: '3.3V', notes: 'GNSS RX from ESP32 UART1_TX / GP5'})
CREATE (can_vcc:Pin {id: 'can_vcc', device: 'sn65', connector: 'sn65_logic_power_connector', name: 'VCC', pin_number: 1, type: 'power_in', voltage: '3.3V', position_frame: 'sn65_component_side_xz_v1', position_x_mm: 6.4852, position_y_mm: 9.0156, physical_edge: 'logic-header end', notes: 'Top pin in component-side reference view.'})
CREATE (can_gnd:Pin {id: 'can_gnd', device: 'sn65', connector: 'sn65_logic_power_connector', name: 'GND', pin_number: 2, type: 'ground', position_frame: 'sn65_component_side_xz_v1', position_x_mm: 6.4852, position_y_mm: 6.4956, physical_edge: 'logic-header end'})
CREATE (can_rxd:Pin {id: 'can_rxd', device: 'sn65', connector: 'sn65_logic_power_connector', name: 'RXD', pin_number: 3, type: 'signal', direction: 'OUT', logic: '3.3V', position_frame: 'sn65_component_side_xz_v1', position_x_mm: 6.4852, position_y_mm: 3.9756, physical_edge: 'logic-header end', notes: 'CAN logic receive data to ESP32 GPIO8/TWAI_RX'})
CREATE (can_txd:Pin {id: 'can_txd', device: 'sn65', connector: 'sn65_logic_power_connector', name: 'TXD', pin_number: 4, type: 'signal', direction: 'IN', logic: '3.3V', position_frame: 'sn65_component_side_xz_v1', position_x_mm: 6.4852, position_y_mm: 1.4556, physical_edge: 'logic-header end', notes: 'CAN logic transmit data from ESP32 GPIO9/TWAI_TX; may remain undriven in listen-only mode'})
CREATE (can_h:Pin {id: 'can_h', device: 'sn65', name: 'CANH logical signal', type: 'can_diff', direction: 'BIDIR', logical_signal: true, physical_contacts: 2, notes: 'CAN differential high is exposed at the screw terminal and a parallel plated pad.'})
CREATE (can_l:Pin {id: 'can_l', device: 'sn65', name: 'CANL logical signal', type: 'can_diff', direction: 'BIDIR', logical_signal: true, physical_contacts: 2, notes: 'CAN differential low is exposed at the screw terminal and a parallel plated pad.'})
CREATE (can_l_screw:Pin {id: 'can_l_screw', device: 'sn65', connector: 'sn65_can_screw_terminal', name: 'CANL screw terminal', display_position: 1, signal: 'CAN-L', polarity: '-', type: 'can_diff_contact', preferred_connection: true, position_frame: 'sn65_component_side_xz_v1', position_x_mm: 28.4820, position_y_mm: 7.9591, notes: 'Upper screw terminal in component-side reference view.'})
CREATE (can_h_screw:Pin {id: 'can_h_screw', device: 'sn65', connector: 'sn65_can_screw_terminal', name: 'CANH screw terminal', display_position: 2, signal: 'CAN-H', polarity: '+', type: 'can_diff_contact', preferred_connection: true, position_frame: 'sn65_component_side_xz_v1', position_x_mm: 28.4820, position_y_mm: 3.2200, notes: 'Lower screw terminal in component-side reference view.'})
CREATE (can_l_pad:Pin {id: 'can_l_pad', device: 'sn65', connector: 'sn65_can_parallel_pads', name: 'CANL parallel pad', display_position: 1, signal: 'CAN-L', polarity: '-', type: 'can_diff_contact', preferred_connection: false, position_frame: 'sn65_component_side_xz_v1', position_x_mm: 22.5881, position_y_mm: 6.5008, notes: 'Electrically parallel with CANL screw terminal.'})
CREATE (can_h_pad:Pin {id: 'can_h_pad', device: 'sn65', connector: 'sn65_can_parallel_pads', name: 'CANH parallel pad', display_position: 2, signal: 'CAN-H', polarity: '+', type: 'can_diff_contact', preferred_connection: false, position_frame: 'sn65_component_side_xz_v1', position_x_mm: 22.5881, position_y_mm: 3.9808, notes: 'Electrically parallel with CANH screw terminal.'})
CREATE (backplane_can_jst_pin1:Pin {id: 'backplane_can_jst_pin1', connector: 'backplane_can_jst_xh_female', name: 'Pin 1 CANL', pin_number: 1, signal: 'CAN-L', polarity: '-', type: 'can_diff_contact', wire_color: 'green'})
CREATE (backplane_can_jst_pin2:Pin {id: 'backplane_can_jst_pin2', connector: 'backplane_can_jst_xh_female', name: 'Pin 2 CANH', pin_number: 2, signal: 'CAN-H', polarity: '+', type: 'can_diff_contact', wire_color: 'white'})
CREATE (can_wire_jst_pin1:Pin {id: 'can_wire_jst_pin1', connector: 'can_wire_jst_xh_male', name: 'Pin 1 CANL', pin_number: 1, signal: 'CAN-L', polarity: '-', type: 'can_diff_contact', wire_color: 'green'})
CREATE (can_wire_jst_pin2:Pin {id: 'can_wire_jst_pin2', connector: 'can_wire_jst_xh_male', name: 'Pin 2 CANH', pin_number: 2, signal: 'CAN-H', polarity: '+', type: 'can_diff_contact', wire_color: 'white'})
CREATE (usb_c_power:Harness {id: 'usb_c_power', name: 'USB-C input power', wires: 2, notes: 'External 5V USB-C power into the ESP32 board. The detailed USB-C cable is outside this harness model.'})
CREATE (power_splitter:Harness {id: 'power_splitter', name: '2-pin 3.3V/GND power splitter', wires: 4, colors: 'red, black', notes: 'ESP32 3V3/GND input split into two 2-pin male power outputs for GPS and CAN module.'})
CREATE (gps_uart:Harness {id: 'gps_uart', name: 'GPS UART signal pair', wires: 2, colors: 'orange, yellow', notes: 'UART signal wires terminating at the onboard LG290P UART connector.'})
CREATE (can_logic_power:Harness {id: 'can_logic_power', name: 'CAN logic/power 4-pin harness', wires: 4, colors: 'red, black, green, blue', notes: 'SN65 VCC, GND, RXD, TXD connector/splitter.'})
CREATE (can_internal_pair:Harness {id: 'can_internal_pair', name: 'Internal CAN pair to backplane JST-XH', wires: 2, colors: 'white, green', pinout: 'pin 1 CANL green; pin 2 CANH white', notes: 'Runs from the SN65 screw terminals to the fixed internal JST-XH housing.', enclosure_id: 'rcx_enclosure', enclosure_scope: 'internal', diagram_level: 'detail'})
CREATE (vehicle_can_taps:Harness {id: 'vehicle_can_taps', name: 'Removable CAN tap lead', wires: 2, colors: 'white, green', pinout: 'pin 1 CANL green; pin 2 CANH white', notes: 'Runs from the removable JST-XH plug to the PosiTap connectors. Vehicle-side conductor colors are defined per vehicle on TAPS_VEHICLE_CAN relationships.', enclosure_scope: 'external', diagram_level: 'detail'})
CREATE (function_UART:Function {name: 'UART', id: 'function:UART'})
CREATE (function_PWM:Function {name: 'PWM', id: 'function:PWM'})
CREATE (function_I2S:Function {name: 'I2S', id: 'function:I2S'})
CREATE (function_ADC:Function {name: 'ADC', id: 'function:ADC'})
CREATE (function_I2C:Function {name: 'I2C', id: 'function:I2C'})
CREATE (function_SPI:Function {name: 'SPI', id: 'function:SPI'})
CREATE (function_GPIO:Function {name: 'GPIO', id: 'function:GPIO'})
CREATE (function_UART1_RX:Function {name: 'UART1_RX', id: 'function:UART1_RX'})
CREATE (function_UART1_TX:Function {name: 'UART1_TX', id: 'function:UART1_TX'})
CREATE (function_TWAI_RX:Function {name: 'TWAI_RX', id: 'function:TWAI_RX'})
CREATE (function_TWAI_TX:Function {name: 'TWAI_TX', id: 'function:TWAI_TX'})
CREATE (function_UART0_TX:Function {name: 'UART0_TX', id: 'function:UART0_TX'})
CREATE (function_UART0_RX:Function {name: 'UART0_RX', id: 'function:UART0_RX'})
CREATE (function_SD_SCLK:Function {name: 'SD_SCLK', id: 'function:SD_SCLK'})
CREATE (function_SD_MOSI:Function {name: 'SD_MOSI', id: 'function:SD_MOSI'})
CREATE (function_SD_MISO:Function {name: 'SD_MISO', id: 'function:SD_MISO'})
CREATE (function_SD_D2:Function {name: 'SD_D2', id: 'function:SD_D2'})
CREATE (function_SD_D1:Function {name: 'SD_D1', id: 'function:SD_D1'})
CREATE (function_SD_CS:Function {name: 'SD_CS', id: 'function:SD_CS'})
CREATE (function_RGB_IO:Function {name: 'RGB_IO', id: 'function:RGB_IO'})
CREATE (function_LCD_RST:Function {name: 'LCD_RST', id: 'function:LCD_RST'})
CREATE (function_LCD_CLK:Function {name: 'LCD_CLK', id: 'function:LCD_CLK'})
CREATE (function_LCD_DC:Function {name: 'LCD_DC', id: 'function:LCD_DC'})
CREATE (function_LCD_CS:Function {name: 'LCD_CS', id: 'function:LCD_CS'})
CREATE (function_LCD_DIN:Function {name: 'LCD_DIN', id: 'function:LCD_DIN'})
CREATE (function_LCD_BL:Function {name: 'LCD_BL', id: 'function:LCD_BL'})
CREATE (function_IMU_INT2:Function {name: 'IMU_INT2', id: 'function:IMU_INT2'})
CREATE (function_IMU_INT1:Function {name: 'IMU_INT1', id: 'function:IMU_INT1'})
CREATE (function_IMU_SCL:Function {name: 'IMU_SCL', id: 'function:IMU_SCL'})
CREATE (function_IMU_SDA:Function {name: 'IMU_SDA', id: 'function:IMU_SDA'})
CREATE (function_BAT_ADC:Function {name: 'BAT_ADC', id: 'function:BAT_ADC'})
CREATE (function_VBAT:Function {name: 'VBAT', id: 'function:VBAT'})
CREATE (function_Ground:Function {name: 'Ground', id: 'function:Ground'})
CREATE (function_3_3V_regulated_output:Function {name: '3.3V regulated output', id: 'function:3.3V regulated output'})
CREATE (function_5V_rail:Function {name: '5V rail', id: 'function:5V rail'})
CREATE (function_USB_UART0_TX:Function {name: 'USB/UART0 TX', id: 'function:USB/UART0 TX'})
CREATE (function_USB_UART0_RX:Function {name: 'USB/UART0 RX', id: 'function:USB/UART0 RX'})
CREATE (esp32_usb_vbus:Pin {id: 'esp32_usb_vbus', device: 'esp32', connector: 'esp32_usb_c', name: 'USB-C VBUS', type: 'power_in', direction: 'IN', voltage: '5V', notes: 'VBUS pin internal to the ESP32 onboard USB-C receptacle; feeds the board 5V rail.'})
CREATE (esp32_usb_gnd:Pin {id: 'esp32_usb_gnd', device: 'esp32', connector: 'esp32_usb_c', name: 'USB-C GND', type: 'ground', notes: 'Ground pin internal to the ESP32 onboard USB-C receptacle; common with board ground.'})

MATCH (a {id: 'esp32'}), (b {id: 'esp32_usb_c'}) CREATE (a)-[:HAS_CONNECTOR {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_5v'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gnd_l'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_3v3'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp0'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp2'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp3'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp4'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp5'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp6'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_txd0'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_rxd0'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_vbat'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gnd_r'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp11'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp10'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp9'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp8'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_gp7'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io12'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io13'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io14'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io15'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io16'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io17'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io18'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io19'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io20'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io21'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io38'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io39'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io40'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io41'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io42'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io43'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io44'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io45'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io46'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io47'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp_io48'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p'}), (b {id: 'lg290p_uart_connector'}) CREATE (a)-[:HAS_CONNECTOR {}]->(b)
MATCH (a {id: 'lg290p'}), (b {id: 'gps_vcc'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p'}), (b {id: 'gps_gnd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p'}), (b {id: 'gps_tx'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p'}), (b {id: 'gps_rx'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'sn65_logic_power_connector'}) CREATE (a)-[:HAS_CONNECTOR {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'sn65_can_screw_terminal'}) CREATE (a)-[:HAS_CONNECTOR {preferred: true}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'sn65_can_parallel_pads'}) CREATE (a)-[:HAS_CONNECTOR {preferred: false}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'sn65_component_side_xz_v1'}) CREATE (a)-[:HAS_COORDINATE_FRAME {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_vcc'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_gnd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_rxd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_txd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_h'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_l'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_l_screw'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_h_screw'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_l_pad'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65'}), (b {id: 'can_h_pad'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65_logic_power_connector'}), (b {id: 'can_vcc'}) CREATE (a)-[:HAS_PIN {position: 1}]->(b)
MATCH (a {id: 'sn65_logic_power_connector'}), (b {id: 'can_gnd'}) CREATE (a)-[:HAS_PIN {position: 2}]->(b)
MATCH (a {id: 'sn65_logic_power_connector'}), (b {id: 'can_rxd'}) CREATE (a)-[:HAS_PIN {position: 3}]->(b)
MATCH (a {id: 'sn65_logic_power_connector'}), (b {id: 'can_txd'}) CREATE (a)-[:HAS_PIN {position: 4}]->(b)
MATCH (a {id: 'sn65_can_screw_terminal'}), (b {id: 'can_l_screw'}) CREATE (a)-[:HAS_PIN {display_position: 1}]->(b)
MATCH (a {id: 'sn65_can_screw_terminal'}), (b {id: 'can_h_screw'}) CREATE (a)-[:HAS_PIN {display_position: 2}]->(b)
MATCH (a {id: 'sn65_can_parallel_pads'}), (b {id: 'can_l_pad'}) CREATE (a)-[:HAS_PIN {display_position: 1}]->(b)
MATCH (a {id: 'sn65_can_parallel_pads'}), (b {id: 'can_h_pad'}) CREATE (a)-[:HAS_PIN {display_position: 2}]->(b)
MATCH (a {id: 'backplane_can_jst_xh_female'}), (b {id: 'backplane_can_jst_pin1'}) CREATE (a)-[:HAS_PIN {position: 1}]->(b)
MATCH (a {id: 'backplane_can_jst_xh_female'}), (b {id: 'backplane_can_jst_pin2'}) CREATE (a)-[:HAS_PIN {position: 2}]->(b)
MATCH (a {id: 'can_wire_jst_xh_male'}), (b {id: 'can_wire_jst_pin1'}) CREATE (a)-[:HAS_PIN {position: 1}]->(b)
MATCH (a {id: 'can_wire_jst_xh_male'}), (b {id: 'can_wire_jst_pin2'}) CREATE (a)-[:HAS_PIN {position: 2}]->(b)
MATCH (a {id: 'can_l_screw'}), (b {id: 'can_l'}) CREATE (a)-[:ELECTRICALLY_COMMON {signal: 'CAN-L'}]->(b)
MATCH (a {id: 'can_l_pad'}), (b {id: 'can_l'}) CREATE (a)-[:ELECTRICALLY_COMMON {signal: 'CAN-L'}]->(b)
MATCH (a {id: 'can_h_screw'}), (b {id: 'can_h'}) CREATE (a)-[:ELECTRICALLY_COMMON {signal: 'CAN-H'}]->(b)
MATCH (a {id: 'can_h_pad'}), (b {id: 'can_h'}) CREATE (a)-[:ELECTRICALLY_COMMON {signal: 'CAN-H'}]->(b)
MATCH (a {id: 'can_l_pad'}), (b {id: 'can_l_screw'}) CREATE (a)-[:PARALLEL_CONTACT {signal: 'CAN-L', preferred_contact: 'can_l_screw'}]->(b)
MATCH (a {id: 'can_h_pad'}), (b {id: 'can_h_screw'}) CREATE (a)-[:PARALLEL_CONTACT {signal: 'CAN-H', preferred_contact: 'can_h_screw'}]->(b)
MATCH (a {id: 'pwr_splitter'}), (b {id: 'pwr_splitter_input'}) CREATE (a)-[:HAS_SUBCONNECTOR {}]->(b)
MATCH (a {id: 'pwr_splitter'}), (b {id: 'pwr_splitter_gps_out'}) CREATE (a)-[:HAS_SUBCONNECTOR {}]->(b)
MATCH (a {id: 'pwr_splitter'}), (b {id: 'pwr_splitter_can_out'}) CREATE (a)-[:HAS_SUBCONNECTOR {}]->(b)
MATCH (a {id: 'esp_3v3'}), (b {id: 'pwr_splitter_input'}) CREATE (a)-[:WIRE {id: 'w_pwr_in_3v3', color: 'red', signal: '3.3V', gauge: '24 AWG', harness: 'power_splitter', physical: 'ESP32 header 3V3(OUT) to power splitter input'}]->(b)
MATCH (a {id: 'esp_gnd_l'}), (b {id: 'pwr_splitter_input'}) CREATE (a)-[:WIRE {id: 'w_pwr_in_gnd', color: 'black', signal: 'GND', gauge: '24 AWG', harness: 'power_splitter', physical: 'ESP32 header GND to power splitter input'}]->(b)
MATCH (a {id: 'pwr_splitter_gps_out'}), (b {id: 'gps_vcc'}) CREATE (a)-[:WIRE {id: 'w_gps_pwr_3v3', color: 'red', signal: '3.3V', gauge: '24 AWG', harness: 'power_splitter', connector_gender: 'male', physical: 'GPS 2-pin power lead output'}]->(b)
MATCH (a {id: 'pwr_splitter_gps_out'}), (b {id: 'gps_gnd'}) CREATE (a)-[:WIRE {id: 'w_gps_pwr_gnd', color: 'black', signal: 'GND', gauge: '24 AWG', harness: 'power_splitter', connector_gender: 'male', physical: 'GPS 2-pin power lead output'}]->(b)
MATCH (a {id: 'pwr_splitter_can_out'}), (b {id: 'can_vcc'}) CREATE (a)-[:WIRE {id: 'w_can_pwr_3v3', color: 'red', signal: '3.3V', gauge: '24 AWG', harness: 'power_splitter', connector_gender: 'male', physical: 'CAN module 2-pin power lead output'}]->(b)
MATCH (a {id: 'pwr_splitter_can_out'}), (b {id: 'can_gnd'}) CREATE (a)-[:WIRE {id: 'w_can_pwr_gnd', color: 'black', signal: 'GND', gauge: '24 AWG', harness: 'power_splitter', connector_gender: 'male', physical: 'CAN module 2-pin power lead output'}]->(b)
MATCH (a {id: 'gps_tx'}), (b {id: 'esp_gp4'}) CREATE (a)-[:WIRE {id: 'w_gps_tx_to_esp_gp4', color: 'orange', signal: 'LG290P_TX_TO_ESP32_UART1_RX', gauge: '26 AWG', harness: 'gps_uart', baud: 460800, physical: 'Terminates at LG290P onboard UART connector'}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'gps_rx'}) CREATE (a)-[:WIRE {id: 'w_esp_gp5_to_gps_rx', color: 'yellow', signal: 'ESP32_UART1_TX_TO_LG290P_RX', gauge: '26 AWG', harness: 'gps_uart', baud: 460800, physical: 'Terminates at LG290P onboard UART connector'}]->(b)
MATCH (a {id: 'can_rxd'}), (b {id: 'esp_gp8'}) CREATE (a)-[:WIRE {id: 'w_can_rxd_to_esp_gp8', color: 'green', signal: 'SN65_RXD_TO_ESP32_TWAI_RX', gauge: '26 AWG', harness: 'can_logic_power', physical: 'SN65 4-pin logic/power connector', notes: 'Correct mapping: GPIO8 = TWAI_RX'}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'can_txd'}) CREATE (a)-[:WIRE {id: 'w_esp_gp9_to_can_txd', color: 'blue', signal: 'ESP32_TWAI_TX_TO_SN65_TXD', gauge: '26 AWG', harness: 'can_logic_power', physical: 'SN65 4-pin logic/power connector', notes: 'Correct mapping: GPIO9 = TWAI_TX; may be configured listen-only and never driven'}]->(b)
MATCH (a {id: 'can_l_screw'}), (b {id: 'backplane_can_jst_pin1'}) CREATE (a)-[:WIRE {id: 'w_can_l_screw_to_backplane_jst_pin1', color: 'green', color_code: 'GRN', signal: 'CAN-L', polarity: '-', gauge: '22 AWG', harness: 'can_internal_pair', notes: 'Preferred screw-terminal connection to fixed internal JST-XH pin 1.'}]->(b)
MATCH (a {id: 'can_h_screw'}), (b {id: 'backplane_can_jst_pin2'}) CREATE (a)-[:WIRE {id: 'w_can_h_screw_to_backplane_jst_pin2', color: 'white', color_code: 'WHT', signal: 'CAN-H', polarity: '+', gauge: '22 AWG', harness: 'can_internal_pair', notes: 'Preferred screw-terminal connection to fixed internal JST-XH pin 2.'}]->(b)
MATCH (a {id: 'backplane_can_jst_xh_female'}), (b {id: 'can_wire_jst_xh_male'}) CREATE (a)-[:MATES_WITH {series: 'JST XH', positions: 2, detachable: true}]->(b)
MATCH (a {id: 'backplane_can_jst_pin1'}), (b {id: 'can_wire_jst_pin1'}) CREATE (a)-[:MATES_WITH {position: 1, signal: 'CAN-L'}]->(b)
MATCH (a {id: 'backplane_can_jst_pin2'}), (b {id: 'can_wire_jst_pin2'}) CREATE (a)-[:MATES_WITH {position: 2, signal: 'CAN-H'}]->(b)
MATCH (a {id: 'can_wire_jst_pin1'}), (b {id: 'positap_can_l'}) CREATE (a)-[:WIRE {id: 'w_can_wire_jst_pin1_to_positap_can_l', color: 'green', color_code: 'GRN', signal: 'CAN-L', polarity: '-', gauge: '22 AWG', harness: 'vehicle_can_taps', notes: 'Removable CAN lead from JST-XH pin 1 to CAN-L PosiTap.'}]->(b)
MATCH (a {id: 'can_wire_jst_pin2'}), (b {id: 'positap_can_h'}) CREATE (a)-[:WIRE {id: 'w_can_wire_jst_pin2_to_positap_can_h', color: 'white', color_code: 'WHT', signal: 'CAN-H', polarity: '+', gauge: '22 AWG', harness: 'vehicle_can_taps', notes: 'Removable CAN lead from JST-XH pin 2 to CAN-H PosiTap.'}]->(b)


// Enclosure membership and exposed interfaces.
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'esp32'}) CREATE (a)-[:CONTAINS {}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'pwr_splitter'}) CREATE (a)-[:CONTAINS {}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'lg290p'}) CREATE (a)-[:CONTAINS {}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'sn65'}) CREATE (a)-[:CONTAINS {}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'backplane_can_jst_xh_female'}) CREATE (a)-[:CONTAINS {}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'esp32_usb_c'}) CREATE (a)-[:EXPOSES_INTERFACE {interface_type: 'power_usb', cover_order: 10}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'lg290p_antenna_connector'}) CREATE (a)-[:EXPOSES_INTERFACE {interface_type: 'gnss_antenna', cover_order: 20}]->(b)
MATCH (a {id: 'rcx_enclosure'}), (b {id: 'backplane_can_jst_xh_female'}) CREATE (a)-[:EXPOSES_INTERFACE {interface_type: 'vehicle_can', cover_order: 30}]->(b)
MATCH (a {id: 'lg290p'}), (b {id: 'lg290p_antenna_connector'}) CREATE (a)-[:HAS_CONNECTOR {role: 'GNSS RF input'}]->(b)
MATCH (a {id: 'external_gnss_antenna'}), (b {id: 'lg290p_antenna_connector'}) CREATE (a)-[:RF_CABLE {signal: 'GNSS RF', direction: 'antenna to receiver', cable_location: 'external', detachable: true}]->(b)

MATCH (a {id: 'porsche_718'}), (b {id: 'porsche_718_can_drive_high'}) CREATE (a)-[:HAS_CAN_BUS {}]->(b)
MATCH (a {id: 'porsche_987_2'}), (b {id: 'porsche_987_2_can_drive'}) CREATE (a)-[:HAS_CAN_BUS {}]->(b)

MATCH (a {id: 'positap_can_h'}), (b {id: 'porsche_718_can_drive_high'}) CREATE (a)-[:TAPS_VEHICLE_CAN {vehicle_id: 'porsche_718', bus_name: 'CAN Drive High', signal: 'CAN-H', polarity: '+', vehicle_wire_color: 'ORG/BLK', vehicle_wire_color_full: 'orange/black'}]->(b)
MATCH (a {id: 'positap_can_l'}), (b {id: 'porsche_718_can_drive_high'}) CREATE (a)-[:TAPS_VEHICLE_CAN {vehicle_id: 'porsche_718', bus_name: 'CAN Drive High', signal: 'CAN-L', polarity: '-', vehicle_wire_color: 'ORG/BRN', vehicle_wire_color_full: 'orange/brown'}]->(b)
MATCH (a {id: 'positap_can_h'}), (b {id: 'porsche_987_2_can_drive'}) CREATE (a)-[:TAPS_VEHICLE_CAN {vehicle_id: 'porsche_987_2', bus_name: 'CAN Drive', signal: 'CAN-H', polarity: '+', vehicle_wire_color: 'YEL/WHT', vehicle_wire_color_full: 'yellow/white'}]->(b)
MATCH (a {id: 'positap_can_l'}), (b {id: 'porsche_987_2_can_drive'}) CREATE (a)-[:TAPS_VEHICLE_CAN {vehicle_id: 'porsche_987_2', bus_name: 'CAN Drive', signal: 'CAN-L', polarity: '-', vehicle_wire_color: 'BLK/WHT', vehicle_wire_color_full: 'black/white'}]->(b)
MATCH (a {id: 'esp_5v'}), (b {id: 'function:5V rail'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gnd_l'}), (b {id: 'function:Ground'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_3v3'}), (b {id: 'function:3.3V regulated output'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp0'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp0'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp0'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp0'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp0'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp0'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp2'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp2'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp2'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp2'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp2'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp2'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp2'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp3'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp3'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp3'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp3'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp3'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp3'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp3'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:UART1_RX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp4'}), (b {id: 'function:UART1_RX'}) CREATE (a)-[:ASSIGNED_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:UART1_TX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp5'}), (b {id: 'function:UART1_TX'}) CREATE (a)-[:ASSIGNED_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp6'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp6'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp6'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp6'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp6'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp6'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp6'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_txd0'}), (b {id: 'function:UART0_TX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_txd0'}), (b {id: 'function:USB/UART0 TX'}) CREATE (a)-[:ASSIGNED_FUNCTION {}]->(b)
MATCH (a {id: 'esp_rxd0'}), (b {id: 'function:UART0_RX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_rxd0'}), (b {id: 'function:USB/UART0 RX'}) CREATE (a)-[:ASSIGNED_FUNCTION {}]->(b)
MATCH (a {id: 'esp_vbat'}), (b {id: 'function:VBAT'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gnd_r'}), (b {id: 'function:Ground'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp11'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp11'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp11'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp11'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp11'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp11'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp11'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp10'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp10'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp10'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp10'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp10'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp10'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp10'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:TWAI_TX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp9'}), (b {id: 'function:TWAI_TX'}) CREATE (a)-[:ASSIGNED_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:TWAI_RX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp8'}), (b {id: 'function:TWAI_RX'}) CREATE (a)-[:ASSIGNED_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp7'}), (b {id: 'function:SPI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp7'}), (b {id: 'function:I2C'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp7'}), (b {id: 'function:ADC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp7'}), (b {id: 'function:I2S'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp7'}), (b {id: 'function:PWM'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp7'}), (b {id: 'function:UART'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_gp7'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io12'}), (b {id: 'function:IMU_INT2'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io12'}), (b {id: 'function:GPIO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io13'}), (b {id: 'function:IMU_INT1'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io14'}), (b {id: 'function:SD_SCLK'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io15'}), (b {id: 'function:SD_MOSI'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io16'}), (b {id: 'function:SD_MISO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io17'}), (b {id: 'function:SD_D2'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io18'}), (b {id: 'function:SD_D1'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io19'}), (b {id: 'function:USB_N'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io20'}), (b {id: 'function:USB_P'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io21'}), (b {id: 'function:SD_CS'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io38'}), (b {id: 'function:RGB_IO'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io39'}), (b {id: 'function:LCD_RST'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io40'}), (b {id: 'function:LCD_CLK'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io41'}), (b {id: 'function:LCD_DC'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io42'}), (b {id: 'function:LCD_CS'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io43'}), (b {id: 'function:UART0_TX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io44'}), (b {id: 'function:UART0_RX'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io45'}), (b {id: 'function:LCD_DIN'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io46'}), (b {id: 'function:LCD_BL'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io47'}), (b {id: 'function:IMU_SCL'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp_io48'}), (b {id: 'function:IMU_SDA'}) CREATE (a)-[:HAS_FUNCTION {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp32_usb_vbus'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32'}), (b {id: 'esp32_usb_gnd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_usb_c'}), (b {id: 'esp32_usb_vbus'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_usb_c'}), (b {id: 'esp32_usb_gnd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'esp32_usb_vbus'}), (b {id: 'esp_5v'}) CREATE (a)-[:ELECTRICALLY_COMMON {net: '5V_USB', notes: 'USB-C VBUS is the source of the board 5V rail.'}]->(b)
MATCH (a {id: 'esp32_usb_gnd'}), (b {id: 'esp_gnd_l'}) CREATE (a)-[:ELECTRICALLY_COMMON {net: 'GND', notes: 'USB-C ground is common with ESP32 external header ground.'}]->(b)
MATCH (a {id: 'esp32_usb_gnd'}), (b {id: 'esp_gnd_r'}) CREATE (a)-[:ELECTRICALLY_COMMON {net: 'GND', notes: 'USB-C ground is common with ESP32 external header ground.'}]->(b)
MATCH (a {id: 'lg290p_uart_connector'}), (b {id: 'gps_vcc'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p_uart_connector'}), (b {id: 'gps_gnd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p_uart_connector'}), (b {id: 'gps_tx'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'lg290p_uart_connector'}), (b {id: 'gps_rx'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65_logic_power_connector'}), (b {id: 'can_vcc'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65_logic_power_connector'}), (b {id: 'can_gnd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65_logic_power_connector'}), (b {id: 'can_rxd'}) CREATE (a)-[:HAS_PIN {}]->(b)
MATCH (a {id: 'sn65_logic_power_connector'}), (b {id: 'can_txd'}) CREATE (a)-[:HAS_PIN {}]->(b)

// ═══════════════════════════════════════════════════════════════════════════
//  FAULT HISTORY — GPS UART signal pair (2026-08-23 to 2026-08-28)
// ═══════════════════════════════════════════════════════════════════════════
// This harness carries 460800-baud NMEA from the LG290P to the ESP32 and RTCM
// corrections back. It is the only link in this model with a confirmed
// intermittent fault history, and its failures present as firmware symptoms,
// so the fingerprint below exists to stop that misattribution recurring.

CREATE (fault_gps_uart_intermittent:FaultMode {id: 'fault_gps_uart_intermittent', name: 'Intermittent GPS UART signal-pair fault', harness: 'gps_uart', period_observed: '2026-08-23 to 2026-08-27', symptom: 'Bimodal per power-cycle and constant within a session: either a clean 20.00 Hz epoch stream with no NMEA checksum failures, or a degraded stream anywhere from 19 Hz down to 0.7 Hz with checksum failures and raw non-ASCII bytes reaching the host. Session damage rates measured across ten sessions ranged 0.00% to 74.03%.', electrical_fingerprint: 'Corrupted bytes are structured, not random: 89.7% match the bit pattern 1_xxx010, identical in every degraded session. Once a byte is corrupted the receiver stays mis-framed for the rest of the line in ~59% of cases, and corrupted lines are LONGER than clean ones, so the receiver produces bytes that were never transmitted. Corruption probability rises with position within a sentence.', ruled_out: 'Die temperature (coolest session was the second-worst; hottest was nearly clean), WiFi and BLE radio activity, RTCM traffic volume, NMEA sentence volume, satellite count, and firmware version. Replacing the LG290P module ALONE did not resolve it.', resolution: 'Replacing the UART wiring harness resolved it completely: 20.00 Hz with zero epoch gaps at or above 80 ms, 0.00% NMEA damage and zero non-ASCII bytes across a 379 s session.', mechanism_status: 'The connection fault is established by substitution. The specific electrical mechanism producing this framing-error signature is NOT established — baud-ratio mismatch and RC edge degradation were both simulated against the observed byte distribution and neither reproduces it.', diagnostic_value: 'Non-ASCII bytes in the sat CSV, or a nonzero ckfail in the firmware 5 s wire counter, are direct evidence of a physical-layer fault on this harness. Neither can be produced by firmware.', source: 'measured'})

MATCH (a {id: 'fault_gps_uart_intermittent'}), (b {id: 'gps_uart'}) CREATE (a)-[:AFFECTS {}]->(b)
MATCH (a {id: 'fault_gps_uart_intermittent'}), (b {id: 'lg290p_uart_connector'}) CREATE (a)-[:SUSPECT_AT {note: 'module-side termination; not isolated to a specific end', source: 'measured'}]->(b)
